// The catalogs and the stores (BUILD_PLAN 2.6, 3.5, 11.3, S4; GAME_DESIGN
// 5.1-5.8, 6.1, E.4; Lead calls 29, 33): content/gear/items.json and
// content/food/items.json, generated by ingest from gear_catalog.json and
// food_catalog.json, read against content/stores/stores.json,
// content/rules/kits.json and content/gear/look_rules.json.
//
// Each gear item carries its numbers, carry, ten_essentials, tags (the
// retired field_guide read as id_book and sketchbook as luxury, E.4), its
// stats (the retired journal_points and journal_points_bonus dropped, and
// any stat whose value is words left in design/data), its tiers as
// overrides, basic, price_usd, origin (the sorted ids of the counters whose
// shelves carry that version: general, gear, desk), look (a palette pair and
// a dither, from look_rules.json) and its estimate flag. Foods carry their
// numbers, prep, needs, tags, sold_at, basic, price_usd and origin. No
// names, flavor or notes: words stay in design/data until a screen's
// session drafts them.
//
// The checks:
//   IG14  info: the retired stats and tags, and the stats that are words
//   IG15  error: basic's hard edges (every item, pack, tier and food has
//         it; a nice one costs more than $0; every trap the general store
//         sells is basic; a standard or premium tier is nice wherever its
//         cheap tier is sold; the beer, the pre-roll and every food not
//         sold at the grocery are nice, every grocery food but the beer
//         basic); warning: a basic item-tier on no M1a shelf and not at the
//         desk (the hiker's own phone aside)
//   IG16  error, the basics guarantee (GAME_DESIGN 5.8, E.4): every need of
//         the ranger's checklist (every row, the worn outfit, the canister)
//         has a basic, non-trap item-tier sold at an open counter or the
//         desk; so does a pack; and every basic stove has a basic fuel it
//         takes
//   IG17  error: a shelf or a kit names an unknown id or tier; warning: an
//         item on two shelves of one store
//   IG19  error: a new item (estimate: true at the source) without evidence
//         for each of its numbers, or a food without its calories' source

const own = (o, k) => o !== null && typeof o === 'object' && Object.prototype.hasOwnProperty.call(o, k);
const byCode = (a, b) => (a < b ? -1 : a > b ? 1 : 0);
const ID = /^[a-z][a-z0-9_]*$/;

/** Where the generated catalogs go. */
export const GEAR_FILE = 'content/gear/items.json';
export const FOOD_FILE = 'content/food/items.json';
/** The tag mappings E.4 asks ingest for. */
export const TAG_MAP = Object.freeze({ field_guide: 'id_book', sketchbook: 'luxury' });
/** The retired collection system's stats (GAME_DESIGN E.4). */
export const RETIRED_STATS = Object.freeze(['journal_points', 'journal_points_bonus']);
/** The beer and the pre-roll, which are nice wherever they're sold (5.8). */
export const LARRY_FOODS = Object.freeze(['beer_hazy_ipa_16oz', 'pre_roll']);
/** Items the hiker owns without a counter: basic, on no shelf (the spec's Q3). */
export const OWN_ITEMS = Object.freeze(['phone']);
/** Food fields carried as data (the rest are words, or S12's effects). */
const FOOD_FIELDS = ['calories', 'weight_oz', 'volume_l', 'volume_repacked_l', 'price_usd', 'basic', 'prep', 'fuel_g', 'water_l', 'morale', 'tags', 'spoils_days', 'crushable', 'needs', 'sold_at', 'kcal_per_oz', 'kcal_per_l', 'age_min', 'requires_flag', 'event_tags', 'overnight_only', 'smellable', 'estimate'];

/** A key for an item-tier: "id" for the standard version, "id:tier" otherwise. */
export const tierKey = (id, tier) => (tier && tier !== 'standard' ? `${id}:${tier}` : id);

/** Is a value code-shaped (an id, a number, a boolean, null, or a list or object of them)? */
function codeShaped(v) {
  if (typeof v === 'string') return ID.test(v);
  if (Array.isArray(v)) return v.every(codeShaped);
  if (v && typeof v === 'object') return Object.values(v).every(codeShaped);
  return true;
}

/**
 * Every version of every gear item and pack: {key, id, tier, kind: 'pack' |
 * 'item', price, basic, tags, stats, ten, trap}.
 * @param {any} gear gear_catalog.json
 */
export function versions(gear) {
  const out = [];
  for (const p of gear.packs || []) out.push({ key: p.id, id: p.id, tier: 'standard', kind: 'pack', price: p.price_usd, basic: p.basic, tags: [...(p.tags || [])], stats: {}, ten: null, trap: (p.tags || []).includes('trap') });
  for (const i of gear.items || []) {
    out.push({ key: i.id, id: i.id, tier: 'standard', kind: 'item', price: i.price_usd, basic: i.basic, tags: [...(i.tags || [])], stats: { ...(i.stats || {}) }, ten: i.ten_essentials ?? null, trap: (i.tags || []).includes('trap') });
    for (const t of i.tiers || []) {
      const tags = [...(i.tags || []).filter((x) => !(t.tags_remove || []).includes(x)), ...(t.tags_add || [])];
      out.push({ key: tierKey(i.id, t.tier), id: i.id, tier: t.tier, kind: 'item', price: t.price_usd, basic: t.basic, tags: [...new Set(tags)], stats: { ...(i.stats || {}), ...(t.stats || {}) }, ten: i.ten_essentials ?? null, trap: tags.includes('trap') });
    }
  }
  return out;
}

/** Does a version meet a need (kits.json), fuel aside? */
export function meets(need, v, notTraps = true) {
  if (notTraps && v.trap) return false;
  if (need.any_tags && !need.any_tags.some((t) => v.tags.includes(t))) return false;
  if (need.all_tags && !need.all_tags.every((t) => v.tags.includes(t))) return false;
  if (need.not_tags && need.not_tags.some((t) => v.tags.includes(t))) return false;
  if (need.ten && v.ten !== need.ten) return false;
  if (need.covers) {
    const c = v.stats.covers;
    if (!Array.isArray(c) || !c.includes(need.covers)) return false;
  }
  return true;
}

/** Is a scope switch on (an unknown one is off)? */
function switchOn(scope, key) {
  const s = scope && scope.switches && scope.switches[key];
  return !!(s && s.on === true);
}

/**
 * Where each version and food is sold: origin by key (sorted counter ids),
 * and the shelf entries' problems.
 * @param {{gear: any, food: any, stores: any, scope: any}} o
 */
export function origins({ gear, food, stores, scope }) {
  const entries = [];
  const err = (where, msg) => entries.push({ code: 'IG17', level: 'error', where: `content/stores/stores.json:${where}`, msg });
  const items = new Map([...(gear.items || []), ...(gear.packs || [])].map((i) => [i.id, i]));
  const foods = new Map((food.items || []).map((f) => [f.id, f]));
  /** @type {Map<string, Set<string>>} key -> counters */
  const where = new Map();
  /** @type {Map<string, Set<string>>} key -> counters whose shelf has it on now (switches) */
  const sold = new Map();
  const add = (m, k, s) => {
    if (!m.has(k)) m.set(k, new Set());
    /** @type {Set<string>} */ (m.get(k)).add(s);
  };
  const open = new Set((scope && scope.stores && scope.stores.open) || []);
  for (const [sid, st] of Object.entries((stores && stores.stores) || {})) {
    const seen = new Map();
    (st.shelves || []).forEach((sh, si) => {
      (sh.items || []).forEach((e, ei) => {
        const path = `stores.${sid}.shelves[${si}].items[${ei}]`;
        const it = items.get(e.id);
        if (!it) return err(path, `"${e.id}" is no item or pack in gear_catalog.json`);
        const tiers = e.tiers || ['standard'];
        for (const t of tiers) {
          if (t !== 'standard' && !(it.tiers || []).some((x) => x.tier === t)) {
            err(path, `${e.id} has no ${t} tier`);
            continue;
          }
          const k = tierKey(e.id, t);
          if (seen.has(k)) entries.push({ code: 'IG17', level: 'warn', where: `content/stores/stores.json:${path}`, msg: `${k} is also on ${sid}'s ${seen.get(k)} shelf` });
          seen.set(k, sh.id);
          add(where, k, sid);
          if (open.has(sid) && (!e.switch || switchOn(scope, e.switch))) add(sold, k, sid);
        }
        if (e.switch && !(scope && scope.switches && own(scope.switches, e.switch))) err(path, `the switch "${e.switch}" is not in the scope file`);
        return undefined;
      });
      if (sh.foods) {
        const f = sh.foods;
        for (const [id, x] of foods) {
          const at = (x.sold_at || []).includes(f.sold_at);
          if ((at && !(f.minus || []).includes(id)) || (f.plus || []).includes(id)) {
            add(where, `food:${id}`, sid);
            if (open.has(sid)) add(sold, `food:${id}`, sid);
          }
        }
        for (const id of [...(f.minus || []), ...(f.plus || [])]) if (!foods.has(id)) err(`stores.${sid}.shelves[${si}].foods`, `"${id}" is no food in food_catalog.json`);
      }
    });
    const cooler = st.cooler;
    if (cooler) {
      for (const id of cooler.items || []) {
        if (!foods.has(id)) err(`stores.${sid}.cooler`, `"${id}" is no food`);
        add(where, `food:${id}`, sid);
        if (open.has(sid) && (!cooler.switch || switchOn(scope, cooler.switch))) add(sold, `food:${id}`, sid);
      }
    }
    for (const id of st.items || []) if (!foods.has(id) && !items.has(id)) err(`stores.${sid}.items`, `"${id}" is in no catalog`);
  }
  const desk = (stores && stores.desk) || {};
  for (const id of [...(desk.loans || []), ...(desk.issues || [])]) {
    if (!items.has(id)) err('desk', `"${id}" is no item`);
    add(where, id, 'desk');
    if (scope && scope.stores && scope.stores.desk) add(sold, id, 'desk');
  }
  const sorted = (m) => new Map([...m].map(([k, s]) => [k, [...s].sort(byCode)]));
  return { where: sorted(where), sold: sorted(sold), entries };
}

/**
 * The basics guarantee (IG16): the problems, one per unmet need.
 * @param {{gear: any, kits: any, sold: Map<string, string[]>}} o
 * @returns {{code: string, level: string, where: string, msg: string}[]}
 */
export function guarantee({ gear, kits, sold }) {
  const out = [];
  const cl = kits && kits.checklist;
  if (!cl) return [{ code: 'IG16', level: 'error', where: 'content/rules/kits.json', msg: 'no checklist: the basics guarantee has nothing to check' }];
  const free = versions(gear).filter((v) => v.basic === true && !v.trap && (sold.get(v.key) || []).length);
  const fail = (row, need, why = '') => out.push({ code: 'IG16', level: 'error', where: `content/rules/kits.json:checklist.${row}.${need}`, msg: `no free basic for the checklist row "${row}", need "${need}"${why}` });
  const needs = [...Object.entries(cl.needs || {}).flatMap(([row, list]) => list.map((n) => [row, n])), ...(cl.worn || []).map((n) => ['worn', n]), ...(cl.canister ? [['canister', cl.canister]] : [])];
  for (const [row, n] of needs) {
    if (n.fuel_for) {
      const stoves = free.filter((v) => v.tags.includes(n.fuel_for) && v.kind === 'item');
      if (!stoves.length) fail(row, n.id, ` (no basic ${n.fuel_for} to fuel)`);
      for (const s of stoves) {
        const wants = s.tags.filter((t) => own(cl.fuels || {}, t)).map((t) => cl.fuels[t]);
        if (!wants.length) {
          fail(row, n.id, ` (the basic stove ${s.key} names no fuel the checklist knows)`);
          continue;
        }
        if (!free.some((v) => wants.some((w) => v.tags.includes(w)))) fail(row, n.id, ` (the basic stove ${s.key} needs ${wants.join(' or ')})`);
      }
      continue;
    }
    if (!free.some((v) => v.kind === 'item' && meets(n, v, cl.not_traps !== false))) fail(row, n.id);
  }
  if (!free.some((v) => v.kind === 'pack')) out.push({ code: 'IG16', level: 'error', where: 'design/data/gear_catalog.json:packs', msg: 'no free basic pack: a sensible first kit needs one (GAME_DESIGN 5.8)' });
  return out;
}

/** An item's look, from look_rules.json. */
function lookOf(rules, it, kind) {
  const cat = kind === 'pack' ? 'pack' : it.category;
  const pair = (rules.by_id || {})[it.id] || (rules.by_category || {})[cat] || null;
  const byTag = Object.entries(rules.dither_by_tag || {}).find(([t]) => (it.tags || []).includes(t));
  const dither = (rules.dither_by_id || {})[it.id] || (byTag ? byTag[1] : null);
  return { pair, dither: dither || 'flat', fallback: !own(rules.by_id || {}, it.id) && !dither };
}

/**
 * The catalogs generator: (ctx) => {files, entries, counts, estimates}.
 * @param {any} ctx
 */
export function catalogs(ctx) {
  const entries = [];
  const estimates = [];
  const gear = ctx.sources.gear_catalog;
  const food = ctx.sources.food_catalog;
  const { stores, kits, scope } = ctx;
  const rules = ctx.look_rules || {};
  if (!gear || !food || !stores || !kits) {
    entries.push({ code: 'IG01', level: 'error', where: 'design/data', msg: 'the catalogs need gear_catalog.json, food_catalog.json, content/stores/stores.json and content/rules/kits.json' });
    return { files: {}, entries };
  }
  const G = (path) => `design/data/gear_catalog.json:${path}`;
  const F = (path) => `design/data/food_catalog.json:${path}`;
  const e15 = (where, msg) => entries.push({ code: 'IG15', level: 'error', where, msg });
  const o = origins({ gear, food, stores, scope });
  entries.push(...o.entries);
  const vs = versions(gear);
  const byKey = new Map(vs.map((v) => [v.key, v]));
  const glossary = gear.tag_glossary || {};

  // IG15: the flags' hard edges.
  for (const v of vs) {
    const where = G(v.kind === 'pack' ? `packs.${v.id}` : v.tier === 'standard' ? `items.${v.id}` : `items.${v.id}.tiers.${v.tier}`);
    if (typeof v.basic !== 'boolean') {
      e15(where, `${v.key} has no basic flag (set it at the source: GAME_DESIGN 5.8, Lead call 29)`);
      continue;
    }
    if (!v.basic && !(v.price > 0)) e15(where, `${v.key} is nice but costs $${v.price}: a nice item has its price`);
    if (v.trap && (o.where.get(v.key) || []).includes('general') && !v.basic) e15(where, `${v.key} is a trap the general store sells, so it's basic (5.8: the flat lay still teaches)`);
    const sold = (k) => (o.sold.get(k) || []).length > 0;
    if (v.tier !== 'cheap' && v.kind === 'item' && v.basic && sold(tierKey(v.id, 'cheap'))) e15(where, `${v.key} is basic, but its cheap tier is sold: the ${v.tier} tier is nice`);
    if (v.basic && !(o.where.get(v.key) || []).length && !OWN_ITEMS.includes(v.id)) entries.push({ code: 'IG15', level: 'warn', where, msg: `${v.key} is basic but on no M1a shelf and not at the desk` });
  }
  for (const f of food.items || []) {
    const where = F(`items.${f.id}`);
    if (typeof f.basic !== 'boolean') {
      e15(where, `${f.id} has no basic flag`);
      continue;
    }
    const grocery = (f.sold_at || []).includes('grocery');
    if (LARRY_FOODS.includes(f.id) && f.basic) e15(where, `${f.id} is basic: the beer and the pre-roll are nice (5.8)`);
    else if (!grocery && f.basic) e15(where, `${f.id} isn't sold at the grocery, so it's nice`);
    else if (grocery && !LARRY_FOODS.includes(f.id) && !f.basic) e15(where, `${f.id} is sold at the grocery, so it's basic (5.8)`);
    if (!f.basic && !(f.price_usd > 0)) e15(where, `${f.id} is nice but costs $${f.price_usd}`);
  }

  // IG16: the basics guarantee.
  entries.push(...guarantee({ gear, kits, sold: o.sold }));

  // IG17: the kits' ids and tiers, and the needs' tags.
  const kitRef = (ref, where) => {
    const [id, tier] = String(ref).split(':');
    if (!byKey.has(tierKey(id, tier || 'standard'))) entries.push({ code: 'IG17', level: 'error', where: `content/rules/kits.json:${where}`, msg: `"${ref}" is no item, pack or tier in gear_catalog.json` });
  };
  for (const [name, k] of Object.entries({ ...(kits.presets || {}), ...(kits.test_kits || {}) })) {
    if (k.pack) kitRef(k.pack, `${name}.pack`);
    for (const f of ['worn', 'carried', 'minus']) for (const r of k[f] || []) kitRef(r, `${name}.${f}`);
  }
  const cl = kits.checklist || {};
  const allNeeds = [...Object.values(cl.needs || {}).flat(), ...(cl.worn || []), ...(cl.canister ? [cl.canister] : [])];
  for (const n of allNeeds) for (const t of [...(n.any_tags || []), ...(n.all_tags || []), ...(n.not_tags || [])]) if (!own(glossary, t)) entries.push({ code: 'IG17', level: 'error', where: `content/rules/kits.json:checklist.${n.id}`, msg: `the tag "${t}" is not in gear_catalog.json's tag_glossary` });
  for (const [need, fuel] of Object.entries(cl.fuels || {})) for (const t of [need, fuel]) if (!own(glossary, t)) entries.push({ code: 'IG17', level: 'error', where: 'content/rules/kits.json:checklist.fuels', msg: `the tag "${t}" is not in the tag_glossary` });

  // IG19: the new items' evidence.
  const newGear = (gear.items || []).filter((i) => i.estimate === true);
  const newFood = (food.items || []).filter((f) => f.estimate === true);
  for (const i of newGear) {
    const ev = i.evidence || {};
    for (const k of ['weight_oz', 'volume_l', 'price_usd', ...(i.stats ? ['stats'] : [])]) if (typeof ev[k] !== 'string' || !ev[k].trim()) entries.push({ code: 'IG19', level: 'error', where: G(`items.${i.id}.evidence`), msg: `the new item ${i.id} has no evidence for ${k}` });
    estimates.push({ where: `${GEAR_FILE}:items.${i.id}`, what: `${i.id}: a new item, every number an estimate`, evidence: Object.entries(ev).map(([k, v]) => `${k}: ${v}`).join('; ') });
  }
  for (const f of newFood) {
    const ev = f.evidence || {};
    for (const k of ['calories', 'weight_oz', 'volume_l', 'price_usd', 'morale']) if (typeof ev[k] !== 'string' || !ev[k].trim()) entries.push({ code: 'IG19', level: 'error', where: F(`items.${f.id}.evidence`), msg: `the new food ${f.id} has no evidence for ${k}` });
    if (typeof f.calories_source !== 'string' || !/^https:\/\/(fdc\.nal\.usda\.gov|[^ ]+)\//.test(f.calories_source)) entries.push({ code: 'IG19', level: 'error', where: F(`items.${f.id}.calories_source`), msg: `the new food ${f.id} has no source for its calories (a real label or USDA FoodData Central, BUILD_PLAN 3.5)` });
    estimates.push({ where: `${FOOD_FILE}:foods.${f.id}`, what: `${f.id}: a new food, every number but its calories an estimate`, evidence: Object.entries(ev).map(([k, v]) => `${k}: ${v}`).join('; ') });
  }

  // The generated gear.
  const dropped = new Map();
  const drop = (k) => dropped.set(k, (dropped.get(k) || 0) + 1);
  const tagsOut = (tags, id) => {
    const out = [];
    for (const t of tags || []) {
      if (own(TAG_MAP, t)) {
        entries.push({ code: 'IG14', level: 'info', where: G(`items.${id}.tags`), msg: `${t} read as ${TAG_MAP[t]} (GAME_DESIGN E.4)` });
        out.push(TAG_MAP[t]);
      } else out.push(t);
    }
    return [...new Set(out)];
  };
  const statsOut = (stats, id) => {
    const out = {};
    for (const [k, v] of Object.entries(stats || {})) {
      if (RETIRED_STATS.includes(k)) {
        entries.push({ code: 'IG14', level: 'info', where: G(`items.${id}.stats.${k}`), msg: `${k} dropped: the collection system is retired (GAME_DESIGN E.4)` });
        continue;
      }
      if (!codeShaped(v)) {
        drop(`stats.${k}`);
        continue;
      }
      out[k] = v;
    }
    return out;
  };
  const fallbacks = [];
  const look = (it, kind) => {
    const l = lookOf(rules, it, kind);
    if (l.fallback) fallbacks.push(it.id);
    return { pair: l.pair, dither: l.dither };
  };
  const packs = {};
  for (const p of gear.packs || []) {
    packs[p.id] = { volume_l: p.volume_l, weight_oz: p.weight_oz, comfortable_max_load_lb: p.comfortable_max_load_lb, price_usd: p.price_usd, basic: p.basic, frame: p.frame, hipbelt: p.hipbelt, outside_slots: p.outside_slots, rain_resistance: p.rain_resistance, tags: tagsOut(p.tags, p.id), origin: o.where.get(p.id) || [], look: look(p, 'pack') };
  }
  const items = {};
  for (const i of gear.items || []) {
    const it = { category: i.category, weight_oz: i.weight_oz, volume_l: i.volume_l, carry: i.carry, price_usd: i.price_usd, basic: i.basic, ten_essentials: i.ten_essentials ?? null, tags: tagsOut(i.tags, i.id), stats: statsOut(i.stats, i.id), origin: o.where.get(i.id) || [], look: look(i, 'item') };
    if (i.tiers) {
      it.tiers = {};
      for (const t of i.tiers) {
        const tt = { weight_oz: t.weight_oz, volume_l: t.volume_l, price_usd: t.price_usd, basic: t.basic, origin: o.where.get(tierKey(i.id, t.tier)) || [] };
        if (t.stats) tt.stats = statsOut(t.stats, i.id);
        if (t.tags_add) tt.tags_add = tagsOut(t.tags_add, i.id);
        if (t.tags_remove) tt.tags_remove = [...t.tags_remove];
        it.tiers[t.tier] = tt;
      }
    }
    if (i.estimate === true) it.estimate = true;
    items[i.id] = it;
  }
  for (const [k, n] of [...dropped].sort((a, b) => byCode(a[0], b[0]))) entries.push({ code: 'IG14', level: 'info', where: G(k), msg: `${n} stat value${n === 1 ? ' is' : 's are'} words: kept in design/data, not carried` });
  if (fallbacks.length) entries.push({ code: 'IG14', level: 'info', where: 'content/gear/look_rules.json', msg: `${fallbacks.length} items on a default look (their category's pair, flat), for S12a's stamps: ${fallbacks.sort(byCode).join(', ')}` });
  const slot7 = Object.values({ ...packs, ...items }).some((x) => x.look.pair && x.look.pair.some((s) => (rules.never_slots || [7]).includes(s)));
  if (slot7) entries.push({ code: 'IG15', level: 'error', where: 'content/gear/look_rules.json', msg: 'a look uses a never slot (gold is the Bonfire Lily\'s only, GAME_DESIGN 11.1)' });

  // The generated foods.
  const foods = {};
  for (const f of food.items || []) {
    const x = {};
    for (const k of FOOD_FIELDS) if (own(f, k)) x[k] = f[k];
    if (f.empty) x.empty = { weight_oz: f.empty.weight_oz, volume_l: f.empty.volume_l, pack_out: f.empty.pack_out === true };
    x.origin = o.where.get(`food:${f.id}`) || [];
    foods[f.id] = x;
  }

  // The basics, by counter, for the report.
  const basics = new Map();
  for (const v of vs) {
    if (v.basic !== true) continue;
    for (const s of o.where.get(v.key) || ['none']) {
      if (!basics.has(s)) basics.set(s, []);
      /** @type {string[]} */ (basics.get(s)).push(v.key);
    }
  }
  for (const [s, list] of [...basics].sort((a, b) => byCode(a[0], b[0]))) entries.push({ code: 'IG15', level: 'info', where: `basics:${s}`, msg: `${list.length} basic: ${list.join(', ')}` });
  // The versions and foods no M1a counter sells: their origin is empty (the glacier tiers' cousins, the boutique's, the pre-roll's).
  const unsold = vs.filter((v) => !(o.where.get(v.key) || []).length).map((v) => v.key);
  if (unsold.length) entries.push({ code: 'IG17', level: 'info', where: 'origin:none', msg: `${unsold.length} item-tiers on no M1a counter, so their origin is empty: ${unsold.join(', ')}` });
  const unsoldFoods = (food.items || []).filter((f) => !(o.where.get(`food:${f.id}`) || []).length).map((f) => f.id);
  if (unsoldFoods.length) entries.push({ code: 'IG17', level: 'info', where: 'origin:none', msg: `${unsoldFoods.length} foods on no M1a counter: ${unsoldFoods.join(', ')}` });
  // B.2's kit against 5.7's shelves: what its pack carries that no M1a counter sells.
  const doubts = [];
  const sensible = (kits.presets || {}).b5_sensible;
  if (sensible) {
    const refs = [sensible.pack, ...(sensible.worn || []), ...(sensible.carried || [])].filter(Boolean);
    const missing = [...new Set(refs.filter((r) => {
      const [id, tier] = r.split(':');
      return !OWN_ITEMS.includes(id) && !(o.where.get(tierKey(id, tier || 'standard')) || []).length;
    }))];
    if (missing.length) doubts.push(`D7. B.2's sensible kit (content/rules/kits.json b5_sensible, the catalog's summer_3_nights_seven_lakes and B.2's additions) carries ${missing.length} things no M1a counter sells by GAME_DESIGN 5.7's shelves: ${missing.join(', ')}. The presets are the harness's kits, not a shopping list, so nothing breaks; but a player can't buy B.2's exact pack in M1a (5.7 sells only the cheap headlamp, and the boutique, with the sun hat and the paperback, opens in M1b). S11 or S12 settles it.`);
  }
  const nBasicFoods = (food.items || []).filter((f) => f.basic === true).length;
  entries.push({ code: 'IG15', level: 'info', where: 'basics:foods', msg: `${nBasicFoods} basic foods (every grocery food but the beer)` });

  const nTiers = (gear.items || []).reduce((a, i) => a + (i.tiers || []).length, 0);
  const files = {
    [GEAR_FILE]: {
      $comment: 'Generated by tools/ingest.mjs (tools/ingest/catalogs.mjs) from design/data/gear_catalog.json, content/stores/stores.json and content/gear/look_rules.json (BUILD_PLAN 2.6, 11.3; GAME_DESIGN 5.7, 5.8, 6.1, E.4): every item\'s numbers, tags, stats, tiers, basic, origin and look; no names or notes. Never hand-edit: run npm run ingest.',
      format: 1,
      packs,
      items,
    },
    [FOOD_FILE]: {
      $comment: 'Generated by tools/ingest.mjs (tools/ingest/catalogs.mjs) from design/data/food_catalog.json and content/stores/stores.json (BUILD_PLAN 2.6; GAME_DESIGN 5.4, 5.7, 5.8): every food\'s numbers, tags, basic and origin; no names or notes. Never hand-edit: run npm run ingest.',
      format: 1,
      foods,
    },
  };
  return {
    files,
    entries,
    estimates,
    doubts,
    counts: [
      ['Gear items', (gear.items || []).length],
      ['Packs', (gear.packs || []).length],
      ['Tiers', nTiers],
      ['Foods', (food.items || []).length],
      ['Basic item-tiers and packs', vs.filter((v) => v.basic === true).length],
      ['Basic foods', nBasicFoods],
    ],
  };
}
