// The climate table (BUILD_PLAN 2.6, S4; GAME_DESIGN 7.5, E.5):
// content/data/climate.json, generated by ingest from park_rules.json
// climate, every number copied, nothing new.
//
//   chain             the one park-wide synoptic Markov chain (7.5): per
//                     month the share of days in each state and the
//                     next-day rows, states in the source's order
//   zones             the six zones' station rows by month: coast from
//                     Quillayute; west_valleys from Clearwater (with the
//                     Hoh's own annual figure); north_mid from Sappho 8 E for
//                     June to October and Port Angeles and the Elwha the
//                     other months; high from the Waterhole and Buckinghorse
//                     SNOTELs; east_high from the Dungeness SNOTEL,
//                     provisional; alpine the research's own estimate (a
//                     lapse from Waterhole), confidence low
//   high_overlays     the High zone's thunder, fog, ridge wind and wet day
//                     given the state (m1a_weather_inputs)
//   freezing_level_ft by month (the Quillayute soundings)
//   snow_free         the SNOTEL melt-outs, as month-day
//   cabin             the cabin's zone (content/park/overlays/park.json)
// Each block keeps the source's computed or estimate flag and its source
// URLs; the report lists the estimates with their evidence. Station names,
// notes and methods are words, and stay in design/data. Typed values here
// (a station's elevation from its name's text, the alpine lapse) are each
// checked against the source's words, so they can't drift.

const own = (o, k) => o !== null && typeof o === 'object' && Object.prototype.hasOwnProperty.call(o, k);
const MONTH = { Jan: 1, Feb: 2, Mar: 3, Apr: 4, May: 5, Jun: 6, Jul: 7, Aug: 8, Sep: 9, Oct: 10, Nov: 11, Dec: 12, January: 1, February: 2, March: 3, April: 4, June: 6, July: 7, August: 8, September: 9, October: 10, November: 11, December: 12 };

/** Where the table goes. */
export const CLIMATE_FILE = 'content/data/climate.json';
/** The chain's states, in the source's order (its method says so). */
export const STATES = Object.freeze(['fair', 'unsettled', 'wet', 'storm']);

/** "June 17" or "May 1 (2015)" or "late April (Apr 29)" to "06-17" (and the year in brackets, when given). */
export function monthDay(text) {
  if (typeof text !== 'string') return null;
  const m = /\b([A-Z][a-z]{2,8})\s+(\d{1,2})\b/.exec(text.replace(/^late\s+[A-Z][a-z]+\s+\(/, '('));
  if (!m || !MONTH[m[1]]) return null;
  const y = /\((\d{4})\)/.exec(text);
  return { md: `${String(MONTH[m[1]]).padStart(2, '0')}-${m[2].padStart(2, '0')}`, year: y ? Number(y[1]) : null };
}

/** A monthly list ({month: "Jan", ...}) as {"1": {...}}, the month key out. */
function byMonth(list) {
  const out = {};
  for (const r of list || []) {
    const { month, ...rest } = r;
    out[String(MONTH[month])] = rest;
  }
  return out;
}

/** A {Jun: {...}} object as {"6": {...}}. */
function monthKeys(o) {
  const out = {};
  for (const [k, v] of Object.entries(o || {})) if (own(MONTH, k)) out[String(MONTH[k])] = v;
  return out;
}

/**
 * The climate generator: (ctx) => {files, entries, counts, estimates}.
 * @param {any} ctx
 */
export function climate(ctx) {
  const entries = [];
  const estimates = [];
  const err = (where, msg) => entries.push({ code: 'IG01', level: 'error', where: `design/data/park_rules.json:${where}`, msg });
  const pr = ctx.sources.park_rules;
  const c = pr && pr.climate;
  if (!c || !c.m1a_weather_inputs) {
    err('climate', 'no climate block (or no m1a_weather_inputs)');
    return { files: {}, entries };
  }
  const urls = new Map((pr.sources || []).map((s) => [s.id, s.url]));
  const used = new Set();
  const src = (ids) => {
    const out = [];
    for (const id of ids || []) {
      const u = urls.get(id);
      if (!u) err('sources', `no source "${id}"`);
      else {
        used.add(u);
        out.push(u);
      }
    }
    return out;
  };
  /** A typed number, checked against the words it comes from. */
  const typed = (where, text, words, value) => {
    if (typeof text !== 'string' || !text.includes(words)) err(where, `expected "${words}" in its words (the typed ${value} can't be checked)`);
    return value;
  };
  const m = c.m1a_weather_inputs;
  const wc = m.weather_chain;

  // The chain.
  const months = {};
  for (const r of wc.monthly || []) {
    const p = STATES.map((s) => r.p[s]);
    const next = STATES.map((s) => r.next_day[s]);
    if (p.some((x) => typeof x !== 'number') || next.some((row) => !Array.isArray(row) || row.length !== 4)) err(`climate.m1a_weather_inputs.weather_chain.monthly.${r.month}`, 'a state is missing');
    months[String(MONTH[r.month])] = { p, next };
  }
  const smoothed = typeof wc.method === 'string' && wc.method.includes('Jun and Jul storm rows') && wc.method.includes('(estimate)');
  if (!smoothed) err('climate.m1a_weather_inputs.weather_chain.method', 'expected its note on the smoothed Jun and Jul storm rows');
  const chain = {
    states: [...STATES],
    months,
    station: 'quillayute',
    period: [typed('climate.m1a_weather_inputs.weather_chain.period', wc.period, '1991-2020', 1991), 2020],
    computed: wc.computed === true,
    estimate_rows: [[6, 'storm'], [7, 'storm']],
    sources: src(wc.source_ids),
  };
  estimates.push({ where: `${CLIMATE_FILE}:chain.estimate_rows`, what: 'the weather chain\'s June and July storm rows', evidence: 'park_rules.json weather_chain.method: they rest on 15 and 7 days, so they are smoothed toward the Aug-Sep shape' });

  // The zones.
  const z = c.zones;
  const sub = z.subalpine_4000_6000ft.stations;
  const rs = z.rain_shadow_lowlands_and_north_valleys.stations;
  const sap = m.north_mid_sol_duc_valley;
  const station = (elev, monthly, more = {}) => ({ elev_ft: elev, months: byMonth(monthly), ...more });
  const alpineText = z.alpine_glacier_6000ft_plus && z.alpine_glacier_6000ft_plus.value;
  const zones = {
    coast: {
      stations: { quillayute: station(typed('climate.zones.coast.proxy_station', z.coast.proxy_station, 'Quillayute Airport (UIL), 180 ft', 180), z.coast.monthly) },
      annual_precip_in: z.coast.annual_precip_in,
      confidence: z.coast.confidence,
      sources: src(z.coast.source_ids),
    },
    west_valleys: {
      stations: { clearwater: station(typed('climate.zones.rain_forest_valleys.proxy_station', z.rain_forest_valleys.proxy_station, 'Clearwater (Queets valley edge, ~250 ft)', 250), z.rain_forest_valleys.monthly, { elev_est: true }) },
      annual_precip_in: z.rain_forest_valleys.annual_precip_in,
      hoh_annual_precip_in: z.rain_forest_valleys.hoh_rain_forest_annual_precip_in.value,
      confidence: z.rain_forest_valleys.confidence,
      sources: src([...z.rain_forest_valleys.source_ids, ...z.rain_forest_valleys.hoh_rain_forest_annual_precip_in.source_ids]),
    },
    north_mid: {
      stations: {
        sappho_8e: station(typed('climate.m1a_weather_inputs.north_mid_sol_duc_valley.station', sap.station, 'Sappho 8 E (USC00457319), 760 ft', 760), sap.monthly),
        port_angeles: station(rs.port_angeles.elev_ft, rs.port_angeles.monthly),
        elwha_ranger_station: station(rs.elwha_ranger_station.elev_ft, rs.elwha_ranger_station.monthly),
      },
      use: {},
      computed: sap.computed === true,
      confidence: z.rain_shadow_lowlands_and_north_valleys.confidence,
      sources: src([...sap.source_ids, ...z.rain_shadow_lowlands_and_north_valleys.source_ids]),
    },
    high: {
      stations: { waterhole_snotel: station(sub.waterhole_snotel.elev_ft, sub.waterhole_snotel.monthly), buckinghorse_snotel: station(sub.buckinghorse_snotel.elev_ft, sub.buckinghorse_snotel.monthly) },
      confidence: z.subalpine_4000_6000ft.confidence,
      sources: src(z.subalpine_4000_6000ft.source_ids),
    },
    east_high: {
      stations: { dungeness_snotel: station(sub.dungeness_snotel.elev_ft, sub.dungeness_snotel.monthly) },
      provisional: true,
      confidence: z.subalpine_4000_6000ft.confidence,
      sources: src(z.subalpine_4000_6000ft.source_ids),
    },
    alpine: {
      from_station: 'waterhole_snotel',
      lapse_f_per_1000ft: typed('climate.zones.alpine_glacier_6000ft_plus.value', alpineText, 'a lapse of ~3.5 F per 1,000 ft', 3.5),
      estimate: true,
      confidence: typed('climate.zones.alpine_glacier_6000ft_plus.confidence', z.alpine_glacier_6000ft_plus.confidence, 'low', 'low'),
      sources: src(z.alpine_glacier_6000ft_plus.source_ids),
    },
  };
  const sapMonths = Object.keys(zones.north_mid.stations.sappho_8e.months);
  for (let k = 1; k <= 12; k++) zones.north_mid.use[String(k)] = sapMonths.includes(String(k)) ? ['sappho_8e'] : ['port_angeles', 'elwha_ranger_station'];
  estimates.push({ where: `${CLIMATE_FILE}:zones.west_valleys.stations.clearwater`, what: 'Clearwater\'s elevation, 250 ft', evidence: 'park_rules.json climate.zones.rain_forest_valleys.proxy_station: "~250 ft"' });
  estimates.push({ where: `${CLIMATE_FILE}:zones.alpine`, what: 'the Alpine zone: Waterhole\'s rows with a lapse of 3.5 F per 1,000 ft', evidence: 'park_rules.json climate.zones.alpine_glacier_6000ft_plus (estimated, confidence low): no long-term station on Mount Olympus' });

  // The High zone's overlays.
  const th = m.thunderstorms_high_zone;
  const fog = m.fog_high_zone;
  const wind = m.ridge_wind_high_zone;
  const wet = wc.high_zone_wet_day_given_state;
  const wetMonths = {};
  for (const [k, v] of Object.entries(wet)) if (own(MONTH, k)) wetMonths[String(MONTH[k])] = STATES.map((s) => v[s]);
  if (!(typeof wet.note === 'string' && wet.note.includes('Storm values for Jul and Aug') && wet.note.includes('estimate'))) err('climate.m1a_weather_inputs.weather_chain.high_zone_wet_day_given_state.note', 'expected its note on the smoothed Jul and Aug storm values');
  const high_overlays = {
    thunder: { months: byMonth(th.monthly), estimate: th.estimate === true, sources: src(th.source_ids) },
    fog: { months: byMonth(fog.monthly), free_air_850hpa: monthKeys(fog.free_air_shares_850hPa), estimate: true, sources: src(fog.source_ids) },
    wind: { months: byMonth(wind.monthly), afternoon_mean_mph_by_state: monthKeys(wind.afternoon_mean_mph_by_state), computed: wind.computed === true, sources: src(wind.source_ids) },
    wet_given_state: { states: [...STATES], months: wetMonths, computed: wet.computed === true, estimate_cells: [[7, 'storm'], [8, 'storm']], sources: src(wc.source_ids) },
  };
  estimates.push({ where: `${CLIMATE_FILE}:high_overlays.thunder`, what: 'High-zone thunder by month and state', evidence: 'park_rules.json thunderstorms_high_zone (estimate: true): design estimates bracketed by measured anchors (Blue Glacier 1957-63, Quillayute, Stampede Pass, NWS)' });
  estimates.push({ where: `${CLIMATE_FILE}:high_overlays.fog`, what: 'High-zone fog by month and state', evidence: 'park_rules.json fog_high_zone: the free-air shares are computed from the Quillayute soundings; the 1.25 ridge factor is an estimate, checked against the Blue Glacier station' });
  estimates.push({ where: `${CLIMATE_FILE}:high_overlays.wet_given_state.estimate_cells`, what: 'the July and August storm values (0.9)', evidence: 'park_rules.json high_zone_wet_day_given_state.note: they rest on 2 and 9 days, smoothed' });

  // Freezing levels and the melt-outs.
  const fl = { months: byMonth(c.freezing_level_ft.monthly), computed: true, confidence: c.freezing_level_ft.confidence, sources: src(c.freezing_level_ft.source_ids) };
  const sf = c.snow_free_dates;
  const melt = (o, where) => {
    const out = {};
    for (const k of ['median', 'earliest', 'latest']) {
      if (!own(o, k)) continue;
      const v = monthDay(o[k]);
      if (!v) err(`climate.snow_free_dates.${where}.${k}`, `"${o[k]}" doesn't read as a month and day`);
      else {
        out[k] = v.md;
        if (v.year !== null) out[`${k}_year`] = v.year;
      }
    }
    if (o.recent) {
      out.recent = {};
      for (const [y, t] of Object.entries(o.recent)) {
        const v = monthDay(t);
        if (!v) err(`climate.snow_free_dates.${where}.recent.${y}`, `"${t}" doesn't read as a month and day`);
        else out.recent[y] = v.md;
      }
    }
    return out;
  };
  const snow_free = {
    waterhole_snotel: melt(sf.waterhole_5010ft, 'waterhole_5010ft'),
    buckinghorse_snotel: melt(sf.buckinghorse_4850ft, 'buckinghorse_4850ft'),
    dungeness_snotel: melt(sf.dungeness_3990ft, 'dungeness_3990ft'),
    computed: true,
    sources: src([typed('climate.snow_free_dates.method', sf.method, 'NRCS SNOTEL daily snow-water-equivalent', 'nrcs_snotel')]),
  };

  const cabinZone = ctx.points && ctx.points.cabin ? ctx.points.cabin.zone : null;
  if (cabinZone !== 'west_valleys') err('climate', `the cabin's zone is ${cabinZone} in content/park/overlays/park.json; the cabin's month climatology reads west_valleys (GAME_DESIGN 7.5)`);
  const body = {
    $comment: 'Generated by tools/ingest.mjs (tools/ingest/climate.mjs) from design/data/park_rules.json climate (BUILD_PLAN 2.6; GAME_DESIGN 7.5, E.5): every number copied as the source has it, by month (1-12), with the source\'s computed and estimate flags; station names and notes stay in design/data. Never hand-edit: run npm run ingest.',
    format: 1,
    chain,
    zones,
    high_overlays,
    freezing_level_ft: fl,
    snow_free,
    cabin: { zone: cabinZone },
    sources: [...used].sort(),
  };
  return { files: { [CLIMATE_FILE]: body }, entries, estimates, counts: [['Climate: chain months, zones', `${Object.keys(months).length}, ${Object.keys(zones).length}`]] };
}
