// The dated conditions overlay (BUILD_PLAN 2.6, S4; GAME_DESIGN 4.6, 4.7,
// E.4, E.5): content/park/conditions/2026.json, generated by ingest.
//
// Every entry is {id, region, from, until | persists, windows?, hours?,
// last_confirmed, stale_after?, stale?, applies_to, effect, extra_mi10?,
// adds_hazards?, hazard_card?, source, confidence, structured}, sorted by
// id. The id is <region>_<from without dashes>_<first applies_to> (a
// segment's "->" written "__"; "status" for an entry with no from date; a
// numeric suffix on a collision). Four sources:
//   1. The structured Sol Duc entries (conditions_2026 with from, until or
//      persists, last_confirmed, applies_to and effect, the game's one-word
//      reading of game_effect, set at the source).
//   2. Region A's statuses written as hazards (trail_closed_2026,
//      possibly_closed_2026), moved here by tools/ingest/regions.mjs.
//   3. park_rules.json current_conditions.roads.items for the roads M1a's
//      drives cross or that GAME_DESIGN 3.3 and 4.6 name (ROADS below): each
//      typed date is checked against the item's own words, so the table
//      can't drift from the source.
//   4. The other regions' entries, which have only a note, a date and a
//      source: kept unstructured (structured: false, effect news, applies to
//      their region), inert until each region's milestone structures its
//      own (IG13, a warning per region, acknowledged).
// The top level carries conditions_date, the research date of the overlay
// (GAME_DESIGN 4.7): the latest researched_on of its inputs, never a clock.
// No English: the research's notes and game_effect stay in design/data.

const byCode = (a, b) => (a < b ? -1 : a > b ? 1 : 0);
const own = (o, k) => o !== null && typeof o === 'object' && Object.prototype.hasOwnProperty.call(o, k);
const ISO = /^\d{4}-\d{2}-\d{2}$/;

/** Where the overlay goes. */
export const CONDITIONS_FILE = 'content/park/conditions/2026.json';
export const CONDITIONS_DIR = 'content/park/conditions';

/** The effects an entry may have (the source's conditions_2026_fields.effect, plus the statuses' and the roads'). */
export const EFFECTS = Object.freeze(['open', 'fire_ban', 'road_closure', 'road_walk', 'single_lane', 'full_snapshot', 'hazard', 'blowdown', 'snow_year', 'news', 'staffing', 'history', 'superseded', 'closure', 'maybe_closed']);

/** The park-wide references an entry may name that aren't graph ids (graphlint's SPECIAL_REFS). */
export const GROUP_REFS = Object.freeze(['all_wilderness_camps']);

/**
 * The roads (park_rules.json current_conditions.roads.items) the overlay
 * structures: those M1a's drives cross, and those GAME_DESIGN 3.3, 4.6 and
 * 4.7 name. `road` is the start of the item's road field; `check` lists
 * words the item's status and date must contain, so a typed date can't
 * drift from the source; last_confirmed must be a date the item or one of
 * its sources gives (its date, or a source's page_date or accessed date);
 * `extra_mi10` is the road walk the source gives for each trailhead cars
 * no longer reach (one entry per distance), with its `evidence` for the
 * report. A road walk names only those old road ends: the graph already
 * walks the road from the trailhead where cars stop, so naming that one
 * would count the walk twice.
 */
export const ROADS = Object.freeze([
  {
    road: 'US 101 Hoh River Bridge',
    applies_to: ['us101_hoh_river_bridge'],
    effect: 'road_closure',
    from: '2026-09-24',
    until: '2026-10-13',
    windows: [['2026-09-24', '2026-09-29'], ['2026-10-01', '2026-10-06'], ['2026-10-08', '2026-10-13']],
    hours: [[5, 17], [5, 12], [5, 12]],
    last_confirmed: '2026-10-08',
    check: ['5 am Sept 24 - 5 pm Sept 29', '5 am Oct 1 - noon Oct 6', '5 am Oct 8 - noon Oct 13, 2026', '2026-10-13'],
    doc: 'GAME_DESIGN 3.3, 4.7: full closures on three windows, the first day from its first hour, the last to its last',
  },
  {
    road: 'US 101 Hoh River Bridge',
    applies_to: ['us101_hoh_river_bridge'],
    effect: 'single_lane',
    from: '2026-07-14',
    persists: true,
    last_confirmed: '2026-10-08',
    check: ['Single-lane alternating traffic', 'since 2026-07-14'],
    doc: "GAME_DESIGN 4.7: the Hoh River Bridge's single lane persists until the overlay is updated",
  },
  {
    road: 'Mora Road',
    applies_to: ['rialto_beach_trailhead'],
    effect: 'road_closure',
    from: '2026-07-08',
    until: '2026-10-15',
    last_confirmed: '2026-10-04',
    check: ['July 8 - Oct 15, 2026', '2026-07-08 to 2026-10-15'],
    doc: 'GAME_DESIGN 4.6, 4.7: Mora Road and Rialto Beach closed through Oct 15, 2026 (sources disagree; NPS says Oct 15)',
  },
  {
    road: 'Olympic Hot Springs Road',
    applies_to: ['whiskey_bend_trailhead'],
    effect: 'road_walk',
    extra_mi10: 65,
    from: '2021-05-07',
    persists: true,
    last_confirmed: '2026-10-04',
    check: ['CLOSED TO VEHICLES at Madison Falls', 'Adds ~6.5 mi to Whiskey Bend', '2021-05-07'],
    evidence: 'GAME_DESIGN 4.6 and E.4 (+6.5 mi to Whiskey Bend); park_rules.json current_conditions.roads ("Adds ~6.5 mi to Whiskey Bend TH", the NPS road page); the graph\'s own road walk from Madison Falls is 6.5 mi',
    doc: 'GAME_DESIGN 4.6, E.4: the Elwha road walk from Madison Falls to Whiskey Bend, +6.5 mi, open-ended',
  },
  {
    road: 'Olympic Hot Springs Road',
    applies_to: ['boulder_creek_trailhead'],
    effect: 'road_walk',
    extra_mi10: 80,
    from: '2021-05-07',
    persists: true,
    last_confirmed: '2026-10-04',
    check: ['CLOSED TO VEHICLES at Madison Falls', '~8 mi to Boulder Creek', '2021-05-07'],
    evidence: 'park_rules.json current_conditions.roads ("~8 mi to Boulder Creek (Appleton Pass/Hot Springs) TH", the NPS road page) and its game_design_notes (+8 mi to Boulder Creek); elwha_hurricane.json trailheads (~8 mi, NPS 7.9 via the bypass); the graph\'s own road walk from Madison Falls is 8.2 mi',
    doc: 'GAME_DESIGN 4.6, E.4: the Elwha road walk from Madison Falls to Boulder Creek, open-ended; the doc gives only Whiskey Bend\'s +6.5, park_rules.json Boulder Creek\'s ~8',
  },
  {
    // The washout is below the current road end (dosewallips_trailhead, where
    // cars park), and the graph already walks the old road from there; the
    // extra miles belong to the old road-end trailhead cars no longer reach,
    // as the Elwha's belong to Whiskey Bend and Boulder Creek, not Madison Falls.
    road: 'Dosewallips Road',
    applies_to: ['dosewallips_ranger_station'],
    effect: 'road_walk',
    extra_mi10: 65,
    from: '2017-08-25',
    persists: true,
    last_confirmed: '2026-02-14',
    check: ['CLOSED TO VEHICLES at washout', '~6.5 mi before the old Dosewallips campground/ranger station', '2017-08-25'],
    evidence: 'GAME_DESIGN 4.6 and E.4 (+6.5 mi); park_rules.json current_conditions.roads ("~6.5 mi before the old Dosewallips campground/ranger station", the NPS road page); the graph\'s own road walk from the road end is 6.5 mi',
    doc: 'GAME_DESIGN 4.6, E.4: the Dosewallips washout, +6.5 mi to the old road end, open-ended',
  },
]);

/** An id-safe slug of a reference ("a->b" becomes "a__b"). */
const slug = (s) => String(s).replace(/->/g, '__').replace(/[^a-z0-9_]/g, '_');

/**
 * The ISO dates a free-text date holds, in order: YYYY-MM-DD as written,
 * YYYY-MM as its first day, a bare year as its January 1.
 * @param {unknown} text
 * @returns {string[]}
 */
export function datesIn(text) {
  if (typeof text !== 'string') return [];
  const out = [];
  for (const m of text.matchAll(/\b((?:19|20)\d{2})(?:-(\d{2})(?:-(\d{2}))?)?\b/g)) out.push(`${m[1]}-${m[2] || '01'}-${m[3] || '01'}`);
  return out;
}

/** park_rules.json's staleness rule (meta.staleness_rule): a claim dated before 2025-01-01 is stale. */
export const STALE_BEFORE = '2025-01-01';

/** The latest ISO date of a list, or null. */
const latest = (list) => (list.length ? [...list].sort(byCode)[list.length - 1] : null);

/**
 * The conditions generator: (ctx) => {files, entries, counts, estimates}.
 * @param {any} ctx ingest's context (the parsed sources and the normalized park)
 */
export function conditions(ctx) {
  /** @type {any[]} */
  const entries = [];
  const estimates = [];
  const list = [];
  /** The evidence of each estimated entry, for the report (never in the file: no English there). */
  const evidenceOf = new Map();
  const err = (where, msg) => entries.push({ code: 'IG13', level: 'error', where, msg });
  const hazardTags = new Set(Object.keys((ctx.vocab && ctx.vocab.hazards && ctx.vocab.hazards.tags) || {}));
  const hazardWord = new Map();
  for (const [tag, words] of Object.entries((ctx.vocab && ctx.vocab.hazards && ctx.vocab.hazards.tags) || {})) for (const w of /** @type {string[]} */ (words)) hazardWord.set(w, tag);
  const dates = [];

  // 1 and 4: the regions' own entries.
  for (const { file, data } of ctx.sources.regions) {
    if (!data || typeof data.region_id !== 'string') continue;
    const region = data.region_id;
    if (typeof data.researched_on === 'string') dates.push(data.researched_on);
    const raw = Array.isArray(data.conditions_2026) ? data.conditions_2026 : [];
    let loose = 0;
    raw.forEach((c, i) => {
      const where = `${region}/conditions_2026[${i}]`;
      if (!c || typeof c !== 'object') return err(where, 'not an entry');
      if (typeof c.source !== 'string' || !/^https?:\/\//.test(c.source)) return err(where, 'needs a source URL');
      const structured = own(c, 'effect') || own(c, 'applies_to');
      if (!structured) {
        const ds = datesIn(c.info_date);
        const from = ds.length ? [...ds].sort(byCode)[0] : null;
        const last = latest(ds);
        if (!last) entries.push({ code: 'IG13', level: 'info', where, msg: 'no date in its info_date: kept undated' });
        const e = { region, from, persists: true, last_confirmed: last, applies_to: [region], effect: 'news', source: c.source, confidence: c.confidence ?? null, structured: false };
        if (last && last < STALE_BEFORE) e.stale = true;
        list.push(e);
        loose++;
        return undefined;
      }
      // A structured entry: every field checked.
      const e = { region, structured: true, source: c.source, confidence: c.confidence ?? null };
      if (!EFFECTS.includes(c.effect)) return err(where, `effect "${c.effect}" is not one of ${EFFECTS.join(', ')} (set it at the source, from game_effect)`);
      e.effect = c.effect;
      if (!ISO.test(c.from)) return err(where, `from "${c.from}" is not an ISO date`);
      e.from = c.from;
      if (own(c, 'until') === (c.persists === true)) return err(where, 'needs exactly one of until and persists: true');
      if (own(c, 'until')) {
        if (!ISO.test(c.until) || c.until < c.from) return err(where, `until "${c.until}" is not an ISO date on or after from`);
        e.until = c.until;
      } else e.persists = true;
      if (!ISO.test(c.last_confirmed)) return err(where, `last_confirmed "${c.last_confirmed}" is not an ISO date`);
      e.last_confirmed = c.last_confirmed;
      for (const k of ['stale_after']) if (own(c, k)) {
        if (!ISO.test(c[k])) return err(where, `${k} "${c[k]}" is not an ISO date`);
        e[k] = c[k];
      }
      if (c.stale === true) e.stale = true;
      if (!Array.isArray(c.applies_to) || !c.applies_to.length || !c.applies_to.every((x) => typeof x === 'string')) return err(where, 'needs applies_to: a list of ids');
      e.applies_to = [...c.applies_to];
      if (own(c, 'windows')) {
        const w = c.windows;
        const ok = Array.isArray(w) && w.every((p) => Array.isArray(p) && p.length === 2 && ISO.test(p[0]) && ISO.test(p[1]) && p[0] <= p[1] && p[0] >= e.from && (!e.until || p[1] <= e.until));
        if (!ok) return err(where, 'windows must be [from, until] ISO date pairs inside the entry\'s dates');
        e.windows = w.map((p) => [p[0], p[1]]);
      }
      if (e.effect === 'road_closure' && !e.windows && !e.until) return err(where, 'a road_closure needs windows or an until date');
      if (own(c, 'adds_hazards')) {
        const tags = [];
        for (const h of c.adds_hazards) {
          const t = hazardTags.has(h) ? h : hazardWord.get(h);
          if (!t) return err(where, `adds_hazards "${h}" is no canonical hazard tag (content/park/vocab/hazards.json)`);
          tags.push(t);
        }
        e.adds_hazards = [...new Set(tags)].sort(byCode);
      }
      if (e.effect === 'hazard' && !e.adds_hazards) return err(where, 'a hazard entry needs adds_hazards');
      if (c.hazard_card) {
        const h = c.hazard_card;
        e.hazard_card = { id: h.id, where: Array.isArray(h.where) ? [...h.where] : [], mitigations: (Array.isArray(h.mitigations) ? h.mitigations : []).filter((m) => /^[a-z][a-z0-9_]*$/.test(m)) };
      }
      list.push(e);
      return undefined;
    });
    if (loose) entries.push({ code: 'IG13', level: 'warn', where: `${region}/conditions_2026`, msg: `${loose} entr${loose === 1 ? 'y has' : 'ies have'} only a note, a date and a source: kept unstructured (news, inert, applying to the region) until the region's milestone structures them` });
  }

  // 2: the statuses region ingest moved off the segments.
  for (const s of (ctx.park && ctx.park.statuses) || []) {
    list.push({ region: s.region, from: s.from, persists: true, last_confirmed: s.last_confirmed, applies_to: [...s.applies_to], effect: s.effect, source: null, confidence: null, structured: true, derived_from: s.derived_from });
  }

  // 3: the roads, from park_rules.json.
  const pr = ctx.sources.park_rules;
  if (pr && pr.meta && typeof pr.meta.researched_on === 'string') dates.push(pr.meta.researched_on);
  const items = (pr && pr.current_conditions && pr.current_conditions.roads && pr.current_conditions.roads.items) || [];
  const byId = new Map(((pr && pr.sources) || []).map((s) => [s.id, s]));
  for (const r of ROADS) {
    const where = `park_rules/roads:${slug(r.road.toLowerCase())}`;
    const item = items.find((it) => typeof it.road === 'string' && it.road.startsWith(r.road));
    if (!item) {
      err(where, `park_rules.json current_conditions.roads.items has no "${r.road}"`);
      continue;
    }
    const words = `${item.status || ''} | ${item.date || ''}`;
    const missing = r.check.filter((w) => !words.includes(w));
    if (missing.length) {
      err(where, `the typed dates no longer match the source: ${missing.map((w) => `"${w}"`).join(', ')} not in its status or date`);
      continue;
    }
    const srcs = (item.source_ids || []).map((id) => byId.get(id)).filter(Boolean);
    const sources = srcs.map((s) => s.url).filter(Boolean);
    const confirmed = [...datesIn(item.date), ...srcs.flatMap((s) => [s.page_date, s.accessed]).filter((d) => typeof d === 'string' && ISO.test(d))];
    if (!confirmed.includes(r.last_confirmed)) {
      err(where, `last_confirmed ${r.last_confirmed} is no date the item or its sources give (${[...new Set(confirmed)].sort(byCode).join(', ')})`);
      continue;
    }
    const e = { region: 'park', from: r.from, last_confirmed: r.last_confirmed, applies_to: [...r.applies_to], effect: r.effect, source: sources[0] || null, confidence: item.confidence ?? null, structured: true };
    if (r.until) e.until = r.until;
    else e.persists = true;
    if (r.windows) e.windows = r.windows.map((p) => [...p]);
    if (r.hours) e.hours = r.hours.map((p) => [...p]);
    if (r.extra_mi10 !== undefined) {
      e.extra_mi10 = r.extra_mi10;
      e.estimate = true;
      if (typeof r.evidence !== 'string' || !r.evidence) err(where, `${r.applies_to.join(', ')}: an estimated road walk needs its evidence`);
      evidenceOf.set(e, r.evidence);
    }
    if (!e.source) err(where, 'no source URL among its source_ids');
    list.push(e);
    entries.push({ code: 'IG13', level: 'info', where, msg: `${r.effect} on ${r.applies_to.join(', ')} from ${r.from}${r.until ? ` to ${r.until}` : ', persisting'}${r.windows ? ` (${r.windows.length} windows)` : ''}${r.extra_mi10 ? `, +${r.extra_mi10 / 10} mi` : ''} (${r.doc})`, scope: true });
  }

  // Ids, then sort.
  const seen = new Map();
  for (const e of list) {
    const base = `${e.region}_${e.from ? e.from.replace(/-/g, '') : 'status'}_${slug(e.applies_to[0])}`;
    const n = (seen.get(base) || 0) + 1;
    seen.set(base, n);
    e.id = n === 1 ? base : `${base}_${n}`;
  }
  list.sort((a, b) => byCode(a.id, b.id));
  list.forEach((e, i) => {
    if (e.estimate) estimates.push({ where: `${CONDITIONS_FILE}:entries[${i}]`, what: `${e.effect} on ${e.applies_to.join(', ')}: +${e.extra_mi10 / 10} mi of road walking`, evidence: evidenceOf.get(e) || '' });
  });
  const conditionsDate = latest(dates.filter((d) => ISO.test(d)));
  if (!conditionsDate) err(CONDITIONS_FILE, 'no researched_on date among its inputs');
  // The later generators (the daylight table's window) read it.
  ctx.conditions_date = conditionsDate;
  const body = {
    $comment: 'Generated by tools/ingest.mjs (tools/ingest/conditions.mjs) from design/data/regions/*.json conditions_2026, the statuses region ingest moved off the segments, and park_rules.json current_conditions.roads (BUILD_PLAN 2.6; GAME_DESIGN 4.6, 4.7, E.4). conditions_date is the research date of the overlay, never a clock. Never hand-edit: run npm run ingest.',
    format: 1,
    conditions_date: conditionsDate,
    entries: list,
  };
  const n = (f) => list.filter(f).length;
  const counts = [
    ['Conditions entries', list.length],
    ['Conditions: structured (Sol Duc, the moved statuses, the roads)', n((e) => e.structured)],
    ['Conditions: unstructured news, by region until its milestone', n((e) => !e.structured)],
    ['Conditions date', conditionsDate],
  ];
  return { files: { [CONDITIONS_FILE]: body }, entries, counts, estimates };
}
