// The gazetteer (BUILD_PLAN 3.2, 10.2, 10.5, S4; GAME_DESIGN 18.2, 4.1):
// content/text/names/places.json, generated by ingest: every real place
// name a screen may show, with its source. Not ours: no approval needed,
// still vetoable.
//
// One entry per merged node (its first region's record), by the node's
// name, cleaned: a parenthetical is moved out ("Seven Lakes Basin (rim
// junction with High Divide Trail)" is Seven Lakes Basin; "Mirror Lake
// (unofficial name)" is Mirror Lake, unofficial). Then:
//   - a name that carries an in-game business name (the research marks
//     them: "(in-game business name: ...)") never enters the file: those
//     businesses get fictional names, which are ours (GAME_DESIGN 5.2);
//   - a name with a lowercase word other than a short connective, or with
//     a "/", is descriptive: a label we made up is ours (18.2), so it goes
//     in not_places, which T16 keeps off every line;
//   - the source is the node's first URL by host, in HOSTS' order, never
//     the elevation service; a node with none is a not_place (IG18).
// content/text/names/places_extra.json (hand) adds the real places that
// aren't nodes; ingest checks that none of its ids is a node's place.

const byCode = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

/** Where the gazetteer goes. */
export const PLACES_FILE = 'content/text/names/places.json';
/** The hosts a name may be sourced from, in order (the first match wins). */
export const HOSTS = Object.freeze([
  (h) => h === 'nps.gov' || h.endsWith('.nps.gov'),
  (h) => h === 'recreation.gov' || h.endsWith('.recreation.gov'),
  (h) => h === 'carto.nationalmap.gov',
  (h) => h === 'usgs.gov' || h.endsWith('.usgs.gov'),
  (h) => h === 'wta.org' || h.endsWith('.wta.org'),
  (h) => h === 'fs.usda.gov' || h.endsWith('.fs.usda.gov'),
  (h) => h === 'openstreetmap.org' || h.endsWith('.openstreetmap.org'),
]);
/** Never a name's source: an elevation service. */
const NEVER = (h) => h === 'epqs.nationalmap.gov';
/** Short connectives a proper name may hold in lowercase. */
export const CONNECTIVES = Object.freeze(['and', 'at', 'of', 'on', 'the', 'to', 'de', 'la']);

/**
 * A node name, cleaned: {text, paren, unofficial, business}.
 * @param {string} name
 */
export function cleanName(name) {
  const m = /^(.*?)\s*\(([^)]*)\)\s*(.*)$/.exec(name);
  const text = m ? `${m[1]}${m[3] ? ` ${m[3]}` : ''}`.trim() : name.trim();
  const paren = m ? m[2] : '';
  return { text, paren, unofficial: /\bunofficial\b/i.test(paren), business: /in-game business name/i.test(name) };
}

/** Is a cleaned name descriptive (ours, not a place)? */
export function descriptive(text) {
  if (text.includes('/')) return true;
  return text.split(/\s+/).some((w) => /^[a-z]/.test(w) && !CONNECTIVES.includes(w));
}

/**
 * The name's source: the first URL whose host comes first in HOSTS.
 * @param {string[]} urls
 * @returns {string | null}
 */
export function nameSource(urls) {
  const hosts = urls.map((u) => {
    try {
      return new URL(u).hostname;
    } catch {
      return '';
    }
  });
  for (const ok of HOSTS) {
    const i = hosts.findIndex((h) => ok(h) && !NEVER(h));
    if (i >= 0) return urls[i];
  }
  return null;
}

/**
 * The gazetteer generator: (ctx) => {files, entries, counts}.
 * @param {any} ctx
 */
export function gazetteer(ctx) {
  const entries = [];
  const park = ctx.park;
  if (!park || !park.nodes) return { files: {}, entries: [{ code: 'IG18', level: 'error', where: PLACES_FILE, msg: 'no park to name' }] };
  const raw = new Map();
  for (const { data } of ctx.sources.regions) {
    if (!data || !Array.isArray(data.nodes)) continue;
    for (const n of data.nodes) if (n && typeof n.id === 'string') raw.set(`${data.region_id}/${n.id}`, n);
  }
  const places = {};
  const notPlaces = {};
  const business = [];
  const noSource = new Map();
  const scope = new Set((ctx.scope && ctx.scope.park && ctx.scope.park.nodes) || []);
  for (const id of [...park.nodes.keys()].sort(byCode)) {
    const region = (park.nodeRegions.get(id) || [])[0];
    const r = raw.get(`${region}/${id}`);
    if (!r || typeof r.name !== 'string') continue;
    const c = cleanName(r.name);
    if (c.business) {
      business.push(id);
      continue;
    }
    if (descriptive(c.text)) {
      notPlaces[id] = { text: c.text, why: 'descriptive', region };
      continue;
    }
    const source = nameSource(park.nodes.get(id).sources || []);
    if (!source) {
      notPlaces[id] = { text: c.text, why: 'no_source', region };
      if (!noSource.has(region)) noSource.set(region, []);
      /** @type {string[]} */ (noSource.get(region)).push(id);
      continue;
    }
    const p = { text: c.text, kind: park.nodes.get(id).type, region, source };
    if (c.unofficial) p.unofficial = true;
    places[id] = p;
  }
  for (const [region, ids] of [...noSource].sort((a, b) => byCode(a[0], b[0]))) {
    const inScope = ids.filter((x) => scope.has(x));
    entries.push({ code: 'IG18', level: inScope.length ? 'error' : 'info', where: `${region}/names`, msg: `${ids.length} node name${ids.length === 1 ? ' has' : 's have'} no usable source (${ids.join(', ')}): not places`, scope: inScope.length > 0 });
  }
  if (business.length) entries.push({ code: 'IG18', level: 'info', where: 'names/business', msg: `${business.length} nodes carry an in-game business name and stay out of the gazetteer (GAME_DESIGN 5.2): ${business.join(', ')}` });
  const inScopeNot = Object.keys(notPlaces).filter((x) => scope.has(x));
  entries.push({ code: 'IG18', level: 'info', where: 'sol_duc_high_divide/names', msg: `the M1a scope: ${[...scope].filter((x) => places[x]).length} places, ${inScopeNot.length} descriptive (${inScopeNot.join(', ')})`, scope: true });

  // places_extra.json: no id may be a node's place, and each has its source.
  const extra = (ctx.places_extra && ctx.places_extra.places) || {};
  for (const [id, p] of Object.entries(extra)) {
    if (places[id] || notPlaces[id]) entries.push({ code: 'IG18', level: 'error', where: `content/text/names/places_extra.json:places.${id}`, msg: `${id} is also a node's name: one id, one place` });
    if (!p || typeof p.source !== 'string' || !/^https?:\/\//.test(p.source)) entries.push({ code: 'IG18', level: 'error', where: `content/text/names/places_extra.json:places.${id}`, msg: 'needs its source URL' });
  }
  const body = {
    $comment: 'Generated by tools/ingest.mjs (tools/ingest/gazetteer.mjs; BUILD_PLAN 3.2, 10.2): every real place name a screen may show, from the park\'s nodes, each with its source. Not ours: no approval needed, still vetoable (GAME_DESIGN 18.2). not_places are descriptive labels (ours, so never on a line as a place: lint T16) and names with no source. Never hand-edit: run npm run ingest.',
    places,
    not_places: notPlaces,
  };
  return {
    files: { [PLACES_FILE]: body },
    entries,
    counts: [
      ['Gazetteer: places (nodes)', Object.keys(places).length],
      ['Gazetteer: not places (descriptive, or no source)', Object.keys(notPlaces).length],
      ['Gazetteer: places_extra.json', Object.keys(extra).length],
    ],
  };
}
