// The permit rules (BUILD_PLAN 2.6, S4; GAME_DESIGN 3.1, 4.3, 4.6, 5.8;
// Lead calls 1, 8, 33): content/park/permits.json, generated by ingest from
// park_rules.json permits and the Sol Duc region's m1a_play_inputs, every
// value copied, nothing new.
//
//   season       the summer and winter permit seasons, as month-day pairs
//   fees         shown on the permit, never paid (5.8)
//   group        the largest party, and the size that needs a group site
//   quota_areas  the ten areas by id; the Sol Duc area (its camps and its
//                online window, read from every camp's quota text, which
//                must agree) and Hoh Lake's structured, the rest ids until
//                their milestones
//   quota        the chance a solo party finds a site, per camp, month and
//                night type (an estimate, with the research's evidence)
//   desk         the WIC-only requests: the odds, the weekend nights, the
//                season, the camps by milestone (an estimate)
//   rangers      the evening visit per camp, rangers met per hour per trail
//                section, the permit check's factors (an estimate)
//   visitors     the no-canister roll (an estimate)
//   loaner       the desk's can, always there (Lead call 33)
// The roll keys and the permit number are engine rules (S10), not data.
// Every typed number is checked against the source's own words, so the
// table can't drift; the words stay in design/data.

const own = (o, k) => o !== null && typeof o === 'object' && Object.prototype.hasOwnProperty.call(o, k);
const MONTH = { Jan: 1, Feb: 2, Mar: 3, Apr: 4, May: 5, Jun: 6, Jul: 7, Aug: 8, Sep: 9, Oct: 10, Nov: 11, Dec: 12, January: 1, February: 2, March: 3, April: 4, June: 6, July: 7, August: 8, September: 9, October: 10, November: 11, December: 12 };

/** Where the rules go. */
export const PERMITS_FILE = 'content/park/permits.json';

/** park_rules.json's ten quota areas, by id: the start of each area's name. */
export const AREAS = Object.freeze({
  ozette_coast: 'Ozette Coast',
  royal_basin: 'Royal Basin',
  lake_constance: 'Lake Constance',
  upper_lena_lake: 'Upper Lena Lake',
  east_fork_quinault: 'East Fork Quinault',
  flapjack_lakes: 'Flapjack Lakes',
  grand_and_badger_valleys: 'Grand Valley and Badger Valley',
  sol_duc_seven_lakes: 'Sol Duc / Seven Lakes Basin',
  hoh_lake_cb_flats: 'Hoh Lake and C.B. Flats',
  hoh_river_trail: 'Hoh River Trail',
});

/** What a camp's quota text says, by area: the phrase that places it, and the online window's words. */
const AREA_TEXT = Object.freeze({
  sol_duc_seven_lakes: { phrase: 'Seven Lakes Basin/High Divide online reservation season', window: /online reservation season ([A-Z][a-z]{2} \d{1,2})-([A-Z][a-z]{2} \d{1,2})/ },
  hoh_lake_cb_flats: { phrase: 'Hoh Lake is a quota area', window: null },
});

/** "May 15 - October 15" (or "Jul 15-Oct 15", or "May 15 to Oct 15") to ["05-15", "10-15"], or null. */
export function mdRange(text) {
  const m = /([A-Z][a-z]+)\s+(\d{1,2})\s*(?:-|to)\s*([A-Z][a-z]+)\s+(\d{1,2})/.exec(String(text));
  if (!m || !MONTH[m[1]] || !MONTH[m[3]]) return null;
  const md = (mo, d) => `${String(MONTH[mo]).padStart(2, '0')}-${d.padStart(2, '0')}`;
  return [md(m[1], m[2]), md(m[3], m[4])];
}

/** A {Jul: x} object as {"7": x}, other keys (a note) left out. */
function monthKeys(o) {
  const out = {};
  for (const [k, v] of Object.entries(o || {})) if (own(MONTH, k)) out[String(MONTH[k])] = v;
  return out;
}

/**
 * The permits generator: (ctx) => {files, entries, counts, estimates, doubts}.
 * @param {any} ctx
 */
export function permits(ctx) {
  const entries = [];
  const estimates = [];
  const doubts = [];
  const err = (where, msg) => entries.push({ code: 'IG13', level: 'error', where, msg });
  const pr = ctx.sources.park_rules;
  const sd = (ctx.sources.regions.find((r) => r.data && r.data.region_id === 'sol_duc_high_divide') || {}).data;
  if (!pr || !pr.permits || !sd || !sd.m1a_play_inputs) {
    err('design/data/park_rules.json:permits', 'needs park_rules.json permits and the Sol Duc region\'s m1a_play_inputs');
    return { files: {}, entries };
  }
  const p = pr.permits;
  const mi = sd.m1a_play_inputs;
  /** A typed value, checked against the words it comes from. */
  const typed = (where, text, words, value) => {
    if (typeof text !== 'string' || !text.includes(words)) err(where, `expected "${words}" in its words (the typed ${JSON.stringify(value)} can't be checked)`);
    return value;
  };
  const urls = new Map((pr.sources || []).map((s) => [s.id, s.url]));
  const used = new Set();
  const src = (ids) => {
    const out = [];
    for (const id of ids || []) {
      if (!urls.has(id)) err('design/data/park_rules.json:sources', `no source "${id}"`);
      else {
        used.add(urls.get(id));
        out.push(urls.get(id));
      }
    }
    return out;
  };

  // Seasons.
  const summer = mdRange(p.seasons.summer.dates);
  const winter = mdRange(p.seasons.winter.dates);
  if (!summer) err('design/data/park_rules.json:permits.seasons.summer.dates', `"${p.seasons.summer.dates}" doesn't read as a range of month-days`);
  if (!winter) err('design/data/park_rules.json:permits.seasons.winter.dates', `"${p.seasons.winter.dates}" doesn't read as a range of month-days`);
  const season = { summer, winter, sources: src([...p.seasons.summer.source_ids, ...p.seasons.winter.source_ids]) };

  // Fees and the group.
  const f = p.fees_2026;
  const fees = { per_adult_per_night_usd: f.per_adult_per_night_usd, per_permit_usd: f.reservation_fee_usd_per_permit, youth_15_and_under_usd: f.youth_15_and_under, shown_not_paid: true, sources: src(f.source_ids) };
  const g = p.group_size;
  const group = {
    max: typed('design/data/park_rules.json:permits.group_size.max', g.max, '12 people', 12),
    group_site_from: typed('design/data/park_rules.json:permits.group_size.large_group', g.large_group, '7-12 people; must use designated group sites', 7),
    sources: src(g.source_ids),
  };

  // Quota areas.
  const quotaCamps = Object.keys(mi.quota_availability.camps || {});
  const nodes = new Map((sd.nodes || []).map((n) => [n.id, n]));
  const quota_areas = {};
  for (const [id, prefix] of Object.entries(AREAS)) {
    const hits = (p.quota_areas.value || []).filter((a) => typeof a.area === 'string' && a.area.startsWith(prefix));
    if (hits.length !== 1) err('design/data/park_rules.json:permits.quota_areas', `"${prefix}" names ${hits.length} areas, not one`);
    quota_areas[id] = { camps: [], online: null, structured: own(AREA_TEXT, id) };
  }
  if ((p.quota_areas.value || []).length !== Object.keys(AREAS).length) err('design/data/park_rules.json:permits.quota_areas', `${(p.quota_areas.value || []).length} areas, not the ${Object.keys(AREAS).length} the table knows`);
  for (const id of quotaCamps) {
    const n = nodes.get(id);
    const text = n && n.camp ? n.camp.reservation_or_quota : null;
    const where = `sol_duc_high_divide/${id}`;
    const area = Object.keys(AREA_TEXT).find((a) => typeof text === 'string' && text.includes(AREA_TEXT[a].phrase));
    if (!area) {
      err(where, 'its quota text places it in no quota area the table knows');
      continue;
    }
    quota_areas[area].camps.push(id);
    const re = AREA_TEXT[area].window;
    if (!re) continue;
    const m = re.exec(text);
    const w = m ? mdRange(`${m[1]}-${m[2]}`) : null;
    if (!w) err(where, 'its quota text gives no online window');
    else if (!quota_areas[area].online) quota_areas[area].online = w;
    else if (quota_areas[area].online.join() !== w.join()) err(where, `its online window ${w.join('..')} disagrees with the area's ${quota_areas[area].online.join('..')}`);
  }
  for (const a of Object.values(quota_areas)) a.camps.sort();
  if (quota_areas.hoh_lake_cb_flats.camps.length) {
    entries.push({ code: 'IG13', level: 'info', where: 'sol_duc_high_divide/hoh_lake', msg: "Hoh Lake's quota text names its area (Hoh Lake and C.B. Flats) but no online window: the window stays null (doubt D6)", scope: true });
    doubts.push("D6. Hoh Lake is in the Hoh Lake and C.B. Flats quota area (park_rules.json), not the Sol Duc area, and its quota text gives no online reservation window, where the other 20 M1a quota camps all say Jul 15-Oct 15. permits.json leaves its window null; park_rules.json's high_elevation_note says high camps are typically reservable mid-July to mid-October. S10 settles the planner's rule for it.");
  }

  // The quota odds.
  const qa = mi.quota_availability;
  const camps = {};
  for (const [id, by] of Object.entries(qa.camps)) camps[id] = monthKeys(by);
  const quota = {
    camps,
    night_types: {
      weekend: typed('sol_duc_high_divide/m1a_play_inputs.quota_availability.night_types', qa.night_types, 'weekend = Friday and Saturday nights', ['fri', 'sat']),
      midweek: typed('sol_duc_high_divide/m1a_play_inputs.quota_availability.night_types', qa.night_types, 'midweek = Sunday to Thursday nights', ['sun', 'mon', 'tue', 'wed', 'thu']),
      labor_day: { nights: typed('sol_duc_high_divide/m1a_play_inputs.quota_availability.night_types', qa.night_types, "Labor Day weekend's Saturday and Sunday nights use half the weekend value", ['sat', 'sun']), of_weekend: 0.5 },
    },
    estimate: mi.estimate === true,
  };
  estimates.push({ where: `${PERMITS_FILE}:quota`, what: 'the quota odds per camp, month and night type', evidence: (mi.evidence || []).join(' ') });

  // The desk.
  const dr = p.desk_requests;
  const desk = {
    p_granted: { midweek: dr.p_granted.midweek, weekend: dr.p_granted.weekend },
    weekend_nights: typed('design/data/park_rules.json:permits.desk_requests.weekend_nights', dr.weekend_nights, 'Friday and Saturday nights', ['fri', 'sat']),
    holiday_sunday: typed('design/data/park_rules.json:permits.desk_requests.weekend_nights', dr.weekend_nights, 'the Sunday of a holiday weekend', true),
    season: mdRange(dr.season),
    m1a: [...dr.m1a_camps],
    m1b: [...dr.m1b_camps],
    phone_only: [...dr.phone_only],
    estimate: dr.estimate === true,
    sources: src(dr.source_ids),
  };
  if (!desk.season) err('design/data/park_rules.json:permits.desk_requests.season', `"${dr.season}" doesn't read as a range of month-days`);
  const mdr = mi.desk_requests;
  if (JSON.stringify(mdr.m1a) !== JSON.stringify(desk.m1a) || JSON.stringify(mdr.m1b) !== JSON.stringify(desk.m1b) || JSON.stringify(mdr.phone_only_m1b) !== JSON.stringify(desk.phone_only)) err('sol_duc_high_divide/m1a_play_inputs.desk_requests', "the region's desk camps disagree with park_rules.json permits.desk_requests");
  estimates.push({ where: `${PERMITS_FILE}:desk`, what: 'the desk request odds, 70% midweek and 40% on weekends', evidence: 'park_rules.json permits.desk_requests (estimate: true); GAME_DESIGN Lead call 1' });

  // The rangers.
  const rp = mi.ranger_presence;
  const visits = {};
  for (const [id, v] of Object.entries(rp.camp_evening_visit.camps)) visits[id] = { midweek: v.midweek, weekend: v.weekend };
  const sections = {};
  for (const [id, s] of Object.entries((mi.trail_traffic && mi.trail_traffic.sections) || {})) if (s.rangers_per_hour) sections[id] = { midweek: s.rangers_per_hour.midweek, weekend: s.rangers_per_hour.weekend };
  const rangers = {
    camp_evening_visit: { camps: visits, weekend_nights: typed('sol_duc_high_divide/m1a_play_inputs.ranger_presence.camp_evening_visit.what', rp.camp_evening_visit.what, 'weekend here means Friday, Saturday and Sunday nights', ['fri', 'sat', 'sun']) },
    on_trail: { per_hour: sections, evening_factor: typed('sol_duc_high_divide/m1a_play_inputs.ranger_presence.on_trail.what', rp.on_trail.what, 'evenings use 0.4 times', 0.4) },
    permit_check: { after_citation_factor: typed('sol_duc_high_divide/m1a_play_inputs.ranger_presence.permit_check.after_a_citation', rp.permit_check.after_a_citation, '1.5 times as likely', 1.5) },
    estimate: mi.estimate === true,
  };
  estimates.push({ where: `${PERMITS_FILE}:rangers`, what: 'ranger visits per camp evening, rangers per hour per section and the permit check', evidence: (mi.evidence || []).join(' ') });

  // The no-canister visitors.
  const fv = mi.food_storage_visitors;
  const visitors = {
    p_visitor_per_night: { ...fv.p_visitor_per_night },
    p_bear_given_visitor: monthKeys(fv.p_bear_given_visitor),
    canister_closed_factor: typed('sol_duc_high_divide/m1a_play_inputs.food_storage_visitors.with_canister_closed', fv.with_canister_closed, 'visitors x 0.15', 0.15),
    estimate: mi.estimate === true,
  };
  estimates.push({ where: `${PERMITS_FILE}:visitors`, what: 'the night visitor roll without a closed canister, and the bear share', evidence: (mi.evidence || []).join(' ') });

  // The desk's can (Lead call 33): the catalog must have it.
  const gear = ctx.sources.gear_catalog;
  const hasLoaner = !!(gear && Array.isArray(gear.items) && gear.items.some((i) => i.id === 'canister_wic_loaner'));
  if (!hasLoaner) err('design/data/gear_catalog.json:items', 'no canister_wic_loaner for the desk to lend (Lead call 33)');
  const loaner = { item: 'canister_wic_loaner', always: true };

  const body = {
    $comment: "Generated by tools/ingest.mjs (tools/ingest/permits.mjs) from design/data/park_rules.json permits and design/data/regions/sol_duc_high_divide.json m1a_play_inputs (BUILD_PLAN 2.6; GAME_DESIGN 3.1, 4.3, 4.6, 5.8; Lead calls 1, 8, 33). Months are 1-12, night types fri to thu; the odds are the research's flagged estimates (the report lists their evidence). Fees are shown on the permit, never paid. Never hand-edit: run npm run ingest.",
    format: 1,
    season,
    fees,
    group,
    quota_areas,
    quota,
    desk,
    rangers,
    visitors,
    loaner,
    sources: [...used].sort(),
  };
  return {
    files: { [PERMITS_FILE]: body },
    entries,
    estimates,
    doubts,
    counts: [['Permits: quota camps (Sol Duc area, Hoh Lake)', `${quotaCamps.length} (${quota_areas.sol_duc_seven_lakes.camps.length}, ${quota_areas.hoh_lake_cb_flats.camps.length})`]],
  };
}
