// The ingest report (BUILD_PLAN 3.2, S4; GAME_DESIGN 4.1, E.4).
//
// Every ingest rule reports what it did as entries
//   {code, level: 'error' | 'warn' | 'info', where, msg}
// where `where` is "<region>/<id>" or "<file>:<path>". The report sorts by
// code, then where (code-unit order). content/park/ingest_known.json
// acknowledges warnings by "<code>:<where>" keys, a key ending in "*"
// covering every where it begins (so "IG04:elwha_hurricane/*" covers a
// region), each with its why: a doc reference and the milestone that fixes
// it. Unexplained: any error, any warning with no acknowledgement, and any
// acknowledgement that matches nothing (stale, so the file can't rot).
// tools/graphlint.mjs acknowledges its own outside-the-scope warnings by
// the same keys.
//
// renderReport() writes content/park/ingest_report.md: the counts, then
// Errors, Warnings (each with its acknowledgement), Fixes (IG04 to IG12
// grouped and counted, the M1a scope's in full; IG22's proposals in full
// everywhere, since a human confirms each), Estimates and Doubts.

/** @typedef {{code: string, level: 'error' | 'warn' | 'info', where: string, msg: string, scope?: boolean}} Entry */

/** The codes, and what each is (BUILD_PLAN S4; the spec's A4). */
export const CODES = Object.freeze({
  IG01: 'source shape',
  IG02: 'shared node',
  IG03: 'shared or paired segment',
  IG04: 'derived gain or loss',
  IG05: 'elevation or position',
  IG06: 'hazard words',
  IG07: 'statuses moved',
  IG08: 'snow windows',
  IG09: 'preset miles',
  IG10: 'rejected preset',
  IG11: 'stale or dropped text',
  IG12: 'Strava',
  IG13: 'conditions',
  IG14: 'catalogs: retired stats and tags',
  IG15: 'catalogs: basic',
  IG16: 'the basics guarantee',
  IG17: 'shelves',
  IG18: 'gazetteer',
  IG19: "new items' evidence",
  IG20: 'an estimate without evidence',
  IG21: 'English in generated content',
  IG22: 'tide limits proposed',
});

/** Codes whose entries are proposals a human confirms one by one (E.4's tide limits): listed in full wherever they are. */
export const IN_FULL = Object.freeze(['IG22']);

const byCode = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

/** Entries in report order: by code, then where, then message. */
export function sortEntries(entries) {
  return [...entries].sort((a, b) => byCode(a.code, b.code) || byCode(a.where, b.where) || byCode(a.msg, b.msg));
}

/** The key an entry is acknowledged by. @param {{code: string, where: string}} e */
export const keyOf = (e) => `${e.code}:${e.where}`;

/**
 * Does an acknowledgement key cover an entry's key?
 * @param {string} ack
 * @param {string} key
 */
export function covers(ack, key) {
  return ack.endsWith('*') ? key.startsWith(ack.slice(0, -1)) : ack === key;
}

/**
 * Sort warnings into acknowledged and not, and find the stale
 * acknowledgements (those matching no warning, among the keys whose codes
 * this run reports).
 * @param {Entry[]} entries
 * @param {Record<string, {why: string}>} known
 * @param {{codes?: (code: string) => boolean}} [o] which codes' acknowledgements this run owns (the rest are another tool's)
 */
export function explain(entries, known, { codes = (c) => c.startsWith('IG') } = {}) {
  const acks = Object.keys(known || {}).filter((k) => k !== '$comment' && codes(k.split(':')[0]));
  const used = new Set();
  /** @type {{entry: Entry, ack: string}[]} */
  const acknowledged = [];
  /** @type {Entry[]} */
  const unexplained = [];
  for (const e of sortEntries(entries)) {
    if (e.level === 'error') {
      unexplained.push(e);
      continue;
    }
    if (e.level !== 'warn') continue;
    const ack = acks.find((a) => covers(a, keyOf(e)));
    if (ack) {
      used.add(ack);
      acknowledged.push({ entry: e, ack });
    } else unexplained.push(e);
  }
  const stale = acks.filter((a) => !used.has(a)).sort(byCode);
  return { acknowledged, unexplained, stale };
}

/** Markdown-safe one-liner. */
const md = (s) => String(s).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');

/**
 * The report as Markdown.
 * @param {object} o
 * @param {Entry[]} o.entries
 * @param {Record<string, {why: string}>} o.known
 * @param {[string, number | string][]} o.counts the counts, in order
 * @param {{where: string, what: string, evidence: string}[]} o.estimates
 * @param {string[]} o.doubts
 * @param {string[]} o.sources the input files
 */
export function renderReport({ entries, known, counts, estimates, doubts, sources }) {
  const sorted = sortEntries(entries);
  const { acknowledged, unexplained, stale } = explain(sorted, known);
  const out = [];
  out.push('# Ingest report');
  out.push('');
  out.push('Generated by `tools/ingest.mjs` (BUILD_PLAN 3.2; GAME_DESIGN 4.1, E.4). Never hand-edit: run `npm run ingest`. This is a doc for authors, not game text. The counts below are the ones GAME_DESIGN 4.1 should quote.');
  out.push('');
  out.push(`Inputs: ${sources.map((s) => `\`${s}\``).join(', ')}.`);
  out.push('');
  out.push('## Counts');
  out.push('');
  out.push('| What | Count |');
  out.push('|---|---|');
  for (const [k, v] of counts) out.push(`| ${md(k)} | ${v} |`);
  out.push('');
  const errors = sorted.filter((e) => e.level === 'error');
  out.push('## Errors');
  out.push('');
  if (!errors.length) out.push('None.');
  for (const e of errors) out.push(`- **${e.code}** \`${e.where}\`: ${md(e.msg)}`);
  out.push('');
  out.push('## Warnings');
  out.push('');
  const warns = sorted.filter((e) => e.level === 'warn');
  out.push(`${warns.length} warning${warns.length === 1 ? '' : 's'}: ${acknowledged.length} acknowledged in \`content/park/ingest_known.json\`, ${warns.length - acknowledged.length} not.`);
  out.push('');
  /** @type {Map<string, Entry[]>} */
  const byAck = new Map();
  for (const { entry, ack } of acknowledged) {
    if (!byAck.has(ack)) byAck.set(ack, []);
    /** @type {Entry[]} */ (byAck.get(ack)).push(entry);
  }
  for (const [ack, list] of [...byAck].sort((a, b) => byCode(a[0], b[0]))) {
    out.push(`### \`${ack}\` (${list.length})`);
    out.push('');
    out.push(`Why: ${md(known[ack].why)}`);
    out.push('');
    for (const e of list) out.push(`- \`${e.where}\`: ${md(e.msg)}`);
    out.push('');
  }
  const loose = unexplained.filter((e) => e.level === 'warn');
  if (loose.length) {
    out.push('### Not acknowledged');
    out.push('');
    for (const e of loose) out.push(`- **${e.code}** \`${e.where}\`: ${md(e.msg)}`);
    out.push('');
  }
  if (stale.length) {
    out.push('### Stale acknowledgements');
    out.push('');
    for (const k of stale) out.push(`- \`${k}\` matches nothing`);
    out.push('');
  }
  out.push('## Fixes');
  out.push('');
  out.push('Every rule ingest applied, by code. The M1a scope\'s are listed in full, and so are the tide limits (IG22, proposals a human confirms one by one); elsewhere each code lists its first entries per region and counts the rest.');
  out.push('');
  const infos = sorted.filter((e) => e.level === 'info');
  for (const code of Object.keys(CODES)) {
    const list = infos.filter((e) => e.code === code);
    if (!list.length) continue;
    out.push(`### ${code}: ${CODES[code]} (${list.length})`);
    out.push('');
    const inScope = list.filter((e) => e.scope);
    const rest = list.filter((e) => !e.scope);
    for (const e of inScope) out.push(`- \`${e.where}\`: ${md(e.msg)} (M1a)`);
    /** @type {Map<string, Entry[]>} */
    const byRegion = new Map();
    for (const e of rest) {
      const r = e.where.split(/[/:]/)[0];
      if (!byRegion.has(r)) byRegion.set(r, []);
      /** @type {Entry[]} */ (byRegion.get(r)).push(e);
    }
    for (const [r, l] of [...byRegion].sort((a, b) => byCode(a[0], b[0]))) {
      const shown = IN_FULL.includes(code) ? l : l.slice(0, 12);
      for (const e of shown) out.push(`- \`${e.where}\`: ${md(e.msg)}`);
      if (l.length > shown.length) out.push(`- ... and ${l.length - shown.length} more in \`${r}\``);
    }
    out.push('');
  }
  out.push('## Estimates');
  out.push('');
  out.push('Every value ingest copies or derives that is an estimate, with its evidence.');
  out.push('');
  if (!estimates.length) out.push('None.');
  for (const e of [...estimates].sort((a, b) => byCode(a.where, b.where) || byCode(a.what, b.what))) out.push(`- \`${e.where}\`: ${md(e.what)}. Evidence: ${md(e.evidence)}`);
  out.push('');
  out.push('## Doubts');
  out.push('');
  out.push('Where the data and the design doc disagree (nothing in GAME_DESIGN is edited here).');
  out.push('');
  if (!doubts.length) out.push('None.');
  for (const d of doubts) out.push(`- ${md(d)}`);
  out.push('');
  return out.join('\n');
}
