// The sun tables (BUILD_PLAN 3.5, S4; GAME_DESIGN 2.2, 7.2, E.5; Lead call
// 34): content/data/quinault_sun.json (the cabin's sky and the daily's
// opening, Lake Quinault's center) and content/data/daylight.json (the
// trail's, the loop's point), generated by ingest, in Node, never on a
// phone.
//
// The method (noaa_zenith_floor_1, pinned by FACT_CHECK.md R3): NOAA's
// solar position equations (https://gml.noaa.gov/grad/solcalc/
// calcdetails.html), evaluated at the instant itself (the Julian day from
// Unix seconds, JD = t / 86400 + 2440587.5, no delta T). An event is the
// moment the true solar zenith crosses 90.833 degrees for sunrise and
// sunset (the sun's upper edge on a sea-level horizon, with standard
// refraction) and 96 degrees for civil dawn and dusk. Each crossing is
// found by bisection on whole Unix seconds, from the previous day's
// instant plus a day, +/- 20 minutes (the whole local day on the first
// day), and the table records the last whole second before the crossing
// (the floor). Pacific time is the US rule since 2007: daylight time from
// the second Sunday of March to the first Sunday of November, at 2 am; a
// day's offset is the one in force at 3 am local. Each row is
// [utc_offset_h, civil_dawn_s, sunrise_s, sunset_s, civil_dusk_s], seconds
// since local midnight, so an event's instant in Unix seconds is the day
// number since 1970-01-01 x 86400 + its seconds - utc_offset_h x 3600.
//
// Floating point: Node's Math.sin and the rest are deterministic for a
// pinned Node (22.23.3, as CI pins), and the ingest check would flag a
// one-second flip after an upgrade for review.

/** The method's name, stamped in each table. */
export const METHOD = 'noaa_zenith_floor_1';
/** The zeniths, in thousandths of a degree. */
export const ZENITH_MILLI = Object.freeze({ rise_set: 90833, civil: 96000 });
/** The time zone rule, by name. */
export const TZ = 'us_pacific_2007';
const DAY = 86400;
const rad = (d) => (d * Math.PI) / 180;
const deg = (r) => (r * 180) / Math.PI;

/**
 * The true solar zenith, in degrees, at an instant (Unix seconds) and a
 * point (north latitude, east longitude), by NOAA's spreadsheet equations.
 * @param {number} t
 * @param {number} lat
 * @param {number} lon
 */
export function zenith(t, lat, lon) {
  const jd = t / DAY + 2440587.5;
  const jc = (jd - 2451545) / 36525;
  const l0 = (280.46646 + jc * (36000.76983 + jc * 0.0003032)) % 360;
  const m = 357.52911 + jc * (35999.05029 - 0.0001537 * jc);
  const e = 0.016708634 - jc * (0.000042037 + 0.0000001267 * jc);
  const c = Math.sin(rad(m)) * (1.914602 - jc * (0.004817 + 0.000014 * jc)) + Math.sin(rad(2 * m)) * (0.019993 - 0.000101 * jc) + Math.sin(rad(3 * m)) * 0.000289;
  const trueLong = l0 + c;
  const omega = 125.04 - 1934.136 * jc;
  const appLong = trueLong - 0.00569 - 0.00478 * Math.sin(rad(omega));
  const meanObliq = 23 + (26 + (21.448 - jc * (46.815 + jc * (0.00059 - jc * 0.001813))) / 60) / 60;
  const obliq = meanObliq + 0.00256 * Math.cos(rad(omega));
  const decl = deg(Math.asin(Math.sin(rad(obliq)) * Math.sin(rad(appLong))));
  const y = Math.tan(rad(obliq / 2)) * Math.tan(rad(obliq / 2));
  const eqTime = 4 * deg(y * Math.sin(2 * rad(l0)) - 2 * e * Math.sin(rad(m)) + 4 * e * y * Math.sin(rad(m)) * Math.cos(2 * rad(l0)) - 0.5 * y * y * Math.sin(4 * rad(l0)) - 1.25 * e * e * Math.sin(2 * rad(m)));
  const utcMin = ((t % DAY) + DAY) % DAY / 60;
  let tst = (utcMin + eqTime + 4 * lon) % 1440;
  if (tst < 0) tst += 1440;
  const ha = tst / 4 < 0 ? tst / 4 + 180 : tst / 4 - 180;
  const cosZ = Math.sin(rad(lat)) * Math.sin(rad(decl)) + Math.cos(rad(lat)) * Math.cos(rad(decl)) * Math.cos(rad(ha));
  return deg(Math.acos(Math.max(-1, Math.min(1, cosZ))));
}

// ---- Calendar (integer) ----------------------------------------------------

/** Days since 1970-01-01 of a civil date (proleptic Gregorian). */
export function dayNumber(y, m, d) {
  const yy = m <= 2 ? y - 1 : y;
  const era = Math.floor(yy / 400);
  const yoe = yy - era * 400;
  const doy = Math.floor((153 * (m + (m > 2 ? -3 : 9)) + 2) / 5) + d - 1;
  const doe = yoe * 365 + Math.floor(yoe / 4) - Math.floor(yoe / 100) + doy;
  return era * 146097 + doe - 719468;
}

/** The civil date of a day number, as [y, m, d]. */
export function civil(n) {
  const z = n + 719468;
  const era = Math.floor(z / 146097);
  const doe = z - era * 146097;
  const yoe = Math.floor((doe - Math.floor(doe / 1460) + Math.floor(doe / 36524) - Math.floor(doe / 146096)) / 365);
  const doy = doe - (365 * yoe + Math.floor(yoe / 4) - Math.floor(yoe / 100));
  const mp = Math.floor((5 * doy + 2) / 153);
  const d = doy - Math.floor((153 * mp + 2) / 5) + 1;
  const m = mp + (mp < 10 ? 3 : -9);
  return [yoe + era * 400 + (m <= 2 ? 1 : 0), m, d];
}

/** "2026-01-01" to its day number. */
export function dayOf(iso) {
  const [y, m, d] = iso.split('-').map(Number);
  return dayNumber(y, m, d);
}

/** A day number to "2026-01-01". */
export function isoOf(n) {
  const [y, m, d] = civil(n);
  return `${y}-${String(m).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
}

/** Weekday of a day number, 0 = Sunday (1970-01-01 was a Thursday). */
const weekday = (n) => (((n + 4) % 7) + 7) % 7;

/** The nth Sunday of a month (n from 1), as a day number. */
export function nthSunday(y, m, n) {
  const first = dayNumber(y, m, 1);
  return first + ((7 - weekday(first)) % 7) + 7 * (n - 1);
}

/** The US daylight time dates of a year since 2007: [the second Sunday of March, the first Sunday of November]. */
export function dstDates(y) {
  return [nthSunday(y, 3, 2), nthSunday(y, 11, 1)];
}

/** Pacific time's UTC offset in hours for a day (the one in force at 3 am local): -7 in daylight time, else -8. */
export function pacificOffset(n) {
  const [y] = civil(n);
  const [a, b] = dstDates(y);
  return n >= a && n < b ? -7 : -8;
}

// ---- The events ------------------------------------------------------------

/**
 * The last whole second before z crosses a zenith in [lo, hi], by
 * bisection, or null when [lo, hi] doesn't bracket it.
 * @param {(t: number) => number} z
 * @param {number} zen degrees
 * @param {number} lo
 * @param {number} hi
 * @param {boolean} rising true for dawn and sunrise (z falls through zen)
 */
function crossing(z, zen, lo, hi, rising) {
  const before = (t) => (rising ? z(t) > zen : z(t) < zen);
  if (!before(lo) || before(hi)) return null;
  while (hi - lo > 1) {
    const mid = Math.floor((lo + hi) / 2);
    if (before(mid)) lo = mid;
    else hi = mid;
  }
  return lo;
}

/** The first crossing in a whole local day, scanning by minutes (the first day's search). */
function scanDay(z, zen, start, rising) {
  for (let t = start; t < start + DAY; t += 60) {
    const r = crossing(z, zen, t, t + 60, rising);
    if (r !== null) return r;
  }
  return null;
}

/**
 * The sun table for a point and a range of days.
 * @param {{lat: number, lon: number, from: string, to: string}} o from and to inclusive ISO dates
 * @returns {{days: number[][], from: string, to: string}}
 */
export function sunTable({ lat, lon, from, to }) {
  const z = (t) => zenith(t, lat, lon);
  const events = [
    { zen: ZENITH_MILLI.civil / 1000, rising: true },
    { zen: ZENITH_MILLI.rise_set / 1000, rising: true },
    { zen: ZENITH_MILLI.rise_set / 1000, rising: false },
    { zen: ZENITH_MILLI.civil / 1000, rising: false },
  ];
  /** @type {(number | null)[]} */
  const prev = [null, null, null, null];
  const days = [];
  for (let n = dayOf(from); n <= dayOf(to); n++) {
    const off = pacificOffset(n);
    const midnight = n * DAY - off * 3600;
    const row = [off];
    events.forEach((ev, i) => {
      let t = null;
      const p = prev[i];
      if (p !== null) t = crossing(z, ev.zen, p + DAY - 1200, p + DAY + 1200, ev.rising);
      if (t === null) t = scanDay(z, ev.zen, ev.rising ? midnight : midnight + DAY / 2, ev.rising);
      if (t === null) throw new Error(`sun: no ${i} event on ${isoOf(n)} at ${lat}, ${lon}`);
      prev[i] = t;
      row.push(t - midnight);
    });
    days.push(row);
  }
  return { days, from, to };
}

/** An event's instant in Unix seconds, from a table row (the spec's formula). */
export function instantOf(from, index, row, k) {
  return (dayOf(from) + index) * DAY + row[k] - row[0] * 3600;
}

/** "H:MM:SS" of seconds since local midnight (for tests and the report). */
export function hms(s) {
  return `${Math.floor(s / 3600)}:${String(Math.floor(s / 60) % 60).padStart(2, '0')}:${String(s % 60).padStart(2, '0')}`;
}

/** "H:MM" of seconds since local midnight, rounded to the nearest minute (half up). */
export function hmRound(s) {
  const m = Math.floor((s + 30) / 60);
  return `${Math.floor(m / 60)}:${String(m % 60).padStart(2, '0')}`;
}

// ---- The generator ---------------------------------------------------------

/** Where the tables go. */
export const QUINAULT_FILE = 'content/data/quinault_sun.json';
export const DAYLIGHT_FILE = 'content/data/daylight.json';
/** The method's source. */
export const NOAA_URL = 'https://gml.noaa.gov/grad/solcalc/calcdetails.html';
/** The cabin's table runs through this day (the spec's call 10: a test warns a year before it ends). */
export const QUINAULT_FROM = '2026-01-01';
export const QUINAULT_TO = '2030-12-31';

/**
 * The sun tables' generator: (ctx) => {files, entries, counts}. The cabin's
 * point is content/park/overlays/park.json's cabin (Lake Quinault's
 * center); the trail's is its daylight_point, from the conditions date
 * (the conditions generator sets ctx.conditions_date) through October 31
 * of the next year (GAME_DESIGN 4.7's window).
 * @param {any} ctx
 */
export function sunGenerator(ctx) {
  const entries = [];
  const pts = ctx.points;
  if (!pts || !pts.cabin || !pts.daylight_point) {
    entries.push({ code: 'IG01', level: 'error', where: 'content/park/overlays/park.json', msg: 'needs cabin and daylight_point for the sun tables' });
    return { files: {}, entries };
  }
  const start = ctx.conditions_date;
  if (typeof start !== 'string') {
    entries.push({ code: 'IG01', level: 'error', where: 'content/park/conditions', msg: 'no conditions date for the daylight table' });
    return { files: {}, entries };
  }
  const to = `${Number(start.slice(0, 4)) + 1}-10-31`;
  const table = (pt, from, until) => {
    const t = sunTable({ lat: pt.lat, lon: pt.lon, from, to: until });
    return {
      format: 1,
      point: [pt.lat, pt.lon],
      point_from: 'content/park/overlays/park.json',
      source: NOAA_URL,
      method: METHOD,
      zenith_milli: { ...ZENITH_MILLI },
      tz: TZ,
      from,
      to: until,
      days: t.days,
    };
  };
  const quinault = { $comment: "Generated by tools/ingest.mjs (tools/sun.mjs; BUILD_PLAN 3.5; GAME_DESIGN 2.2; Lead call 34): the cabin's sun and civil twilight for every day at Lake Quinault's center. Each row is [utc_offset_h, civil_dawn_s, sunrise_s, sunset_s, civil_dusk_s], seconds since local midnight; an instant is the day number x 86400 + seconds - utc_offset_h x 3600. NOAA's equations, the zenith's crossing floored to the second; FACT_CHECK.md R3 is its golden. Never hand-edit: run npm run ingest.", ...table(pts.cabin, QUINAULT_FROM, QUINAULT_TO) };
  const daylight = { $comment: "Generated by tools/ingest.mjs (tools/sun.mjs; GAME_DESIGN 7.2, 4.7, E.5): sunrise, sunset and civil twilight on the loop for every day from the conditions date through the window's end, in quinault_sun.json's format. park_rules.json daylight_loop_2027 is its golden, to the minute. Never hand-edit: run npm run ingest.", ...table(pts.daylight_point, start, to) };
  return {
    files: { [QUINAULT_FILE]: quinault, [DAYLIGHT_FILE]: daylight },
    entries,
    counts: [
      ["The cabin's sun table (days)", `${quinault.days.length}, ${QUINAULT_FROM} to ${QUINAULT_TO}`],
      ['The loop\'s daylight table (days)', `${daylight.days.length}, ${start} to ${to}`],
    ],
  };
}
