import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { makeServer } from '../../tools/serve.mjs';

test('serve: the site lives at the root, as on ophiker.com, with preview at /preview/', async (t) => {
  const dir = mkdtempSync(join(tmpdir(), 'oph-serve-'));
  mkdirSync(join(dir, 'css'));
  mkdirSync(join(dir, 'preview'));
  writeFileSync(join(dir, 'index.html'), '<!doctype html><title>main</title>');
  writeFileSync(join(dir, 'preview', 'index.html'), '<!doctype html><title>preview</title>');
  writeFileSync(join(dir, 'css', 'a.css'), 'body{}');
  writeFileSync(join(dir, 'manifest.webmanifest'), '{}');
  writeFileSync(join(dir, 'sw.js'), '// oph-sw');
  const server = makeServer(dir);
  await new Promise((r) => server.listen(0, '127.0.0.1', r));
  t.after(() => {
    server.close();
    rmSync(dir, { recursive: true, force: true });
  });
  const base = `http://127.0.0.1:${server.address().port}`;
  const get = (p) => fetch(base + p, { redirect: 'manual' });
  let r = await get('/');
  assert.equal(r.status, 200);
  assert.match(r.headers.get('content-type'), /text\/html/);
  assert.match(await r.text(), /<title>main<\/title>/);
  r = await get('/?debug=1');
  assert.equal(r.status, 200, 'a query is fine');
  r = await get('/preview/');
  assert.equal(r.status, 200);
  assert.match(await r.text(), /<title>preview<\/title>/);
  r = await get('/preview');
  assert.equal(r.status, 301, 'a folder without its slash moves to it, as on Pages');
  assert.equal(r.headers.get('location'), '/preview/');
  r = await get('/preview?debug=1');
  assert.equal(r.headers.get('location'), '/preview/?debug=1', 'keeping the query');
  r = await get('/css/a.css');
  assert.equal(r.status, 200);
  assert.match(r.headers.get('content-type'), /text\/css/);
  r = await get('/manifest.webmanifest');
  assert.match(r.headers.get('content-type'), /application\/manifest\+json/);
  r = await get('/sw.js');
  assert.match(r.headers.get('content-type'), /text\/javascript/);
  r = await get('/104-boyz/');
  assert.equal(r.status, 404, 'the old subpath is gone');
  assert.match(r.headers.get('content-type'), /text\/plain/);
  assert.equal((await get('/nope.js')).status, 404);
  assert.notEqual((await get('/%2e%2e/%2e%2e/etc/passwd')).status, 200, 'no way out of the folder');
  assert.notEqual((await get('/..%2f..%2fetc%2fpasswd')).status, 200, 'no way out of the folder');
  assert.notEqual((await get('/preview/..%2f..%2f..%2fetc%2fpasswd')).status, 200, 'no way out of the folder');
  assert.equal((await get('/%E0%A4%A')).status, 400, 'a bad escape is refused');
});
